### ISSUE TITLE
Make package pip installable

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/wfdb-python#1]
Guidelines for making the package installable with pip are at:
https://packaging.python.org/en/latest/distributing/

**Comment by cx1111** [comment]
https://pypi.python.org/pypi/wfdb/0.1.1

Woohoo it works. I do have to convert the readme to rst so that pypi can display it I suppose.

**Comment by tompollard** [comment]
This is excellent Chen :) 

I just successfully installed the package with the following command:

```{bash}
pip install wfdb
```

The readme needs to be changed to `README.rst` (http://docutils.sourceforge.net/rst.html)
