### ISSUE TITLE
rdann does not start from sampfrom input parameter

### ISSUE THREAD

**Issue by gauravbrd** [MIT-LCP/wfdb-python#101]
Reading annotation always outputs the annotations starting from 0th sample. For example, When I try to read annotation from 4000 to 5000 samples, rdann outputs annotations from 0 to 4000 !

**Comment by MishalJasmine** [comment]
I am facing the same issue. Is there any update on this?

**Comment by tompollard** [comment]
@MishalJasmine are you using the latest version of the package? If so, please could you post code to reproduce the issue?
