### ISSUE TITLE
Comparison

### ISSUE THREAD

**Issue by gencee** [MIT-LCP/wfdb-python#105]
Hey guys,
Congratulations on this library. It's very impressive and usefull. I am testing the peak detection on the MIT-BIH dataset. 

It seems to be working well however the comparison function says the performance is low (close to 0 sensitivity in the case of beat 101). From the looks of the comparison function and the plots from the comparitor.plot, it seems everything becomes false as soon as there is one peak is missed or falsely detected.

![index](https://user-images.githubusercontent.com/15327397/36164209-fd501b7e-10eb-11e8-9473-2e7c8a9b7325.png)

**Comment by ChitandaXu** [comment]
I met the same problem.

**Comment by cx1111** [comment]
Thanks for noticing. I think it should be fixed, I tried on a couple of records like 101.

I've added the `benchmark_mitdb` function and tested xqrs using it: 
- http://wfdb.readthedocs.io/en/latest/processing.html#wfdb.processing.benchmark_mitdb

```
 import wfdb
from wfdb.processing import benchmark_mitdb, xqrs_detect
 comparitors, spec, pp, fpr = benchmark_mitdb(xqrs_detect)
```

**Comment by fgr1986** [comment]
May I ask why the comparison does not work when the full annotation.sample is passed to the compare_annotations method, and instead annotation.sample[1:] works well?

**Comment by cx1111** [comment]
Could you give an example of data where this happens?

**Comment by fgr1986** [comment]
My bad, I pre-filtered the signal in a bad way. Please, forget the issue. Sorry for the inconvenience.

**Comment by gencee** [comment]
great thks

**Comment by jbehar** [comment]
Hi Chen, @cx1111 

Line 114 of the Comparitor class: 

self.specificity = float(self.tp) / self.n_ref

I believe this is the sensitivity (TP/(TP+FN)) and not specificity.

Cheers
