### ISSUE TITLE
Downloading databases via dl_database fails

### ISSUE THREAD

**Issue by SimpleConjugate** [MIT-LCP/wfdb-python#106]
When attempting to run

`wfdb.dl_database('ahadb', os.getcwd())`

The following error is returned

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<omitted>/wfdb/io/record.py", line 1365, in dl_database
    r = requests.get(dburl)
NameError: global name 'dburl' is not defined

 I made a quick fix by changing `dburl` to `download.db_index_url`
Which is the correct version?

**Comment by kapec94** [comment]
I confirm the error happens. Code:

    wfdb.dl_database('ptbdb', dl_dir='data/',
                 records=['patient001/s0010_re'],
                 overwrite=False)

Yields:

> Traceback (most recent call last):
  File "<...>\main.py", line 10, in <module>
    overwrite=False)
  File "<...>\wfdb\io\record.py", line 1365, in dl_database
    r = requests.get(dburl)
NameError: name 'dburl' is not defined
