### ISSUE TITLE
ECG txt file to .hea .dat .atr

### ISSUE THREAD

**Issue by Hu-Yu-Lun** [MIT-LCP/wfdb-python#108]
Hi,
I would like to know is it possible to convert the raw ECG signal data into .hea .dat .atr file?
my raw ECG signal data format is like
-116 -113 -113 -115 -117 -123 -128 -130 -130 -125 -124 -124 -126 -131 -134 -135 -137 -135 -128 -126 -129 -133 -137 -138 -138 ...
and the data is from PhilipsECG PageWriter TC

Look forward to your reply,sincerely.

**Comment by alistairewj** [comment]
Using WFDB: https://physionet.org/tutorials/creating-records.shtml

Using WFDB python, make a record object then use wrsamp: http://wfdb.readthedocs.io/en/latest/io.html?highlight=wrsamp
