### ISSUE TITLE
Data loaded incorrectly for format 212 file

### ISSUE THREAD

**Issue by alistairewj** [MIT-LCP/wfdb-python#11]
I think there is some bug in the way negative values are handled... I tried loading in data from v102s - attached here [example-data.zip](https://github.com/MIT-LCP/wfdb-python/files/391147/example-data.zip)

When I load it directly and plot it I get this:

```python
recName = 'v102s'
base_path = '/home/alistairewj/challenge-2015/test/challenge-2015-training-dat/'
sig, fields=readsignal.rdsamp(base_path + recName)
plotwfdb.plotsigs(sig[0:(0+int(fields['fs'])*10),:], fields, title=recName)
```

![figure_1](https://cloud.githubusercontent.com/assets/1282676/17260059/493e7fba-559c-11e6-8d76-3dcbd886ccb1.png)

However if I first read it using the shell rdsamp

```sh
rdsamp -r v102s -c -pS -H > test.csv
```

Then load in this csv directly in python (Note I included the test.csv file in the zip above):

```python
data = np.genfromtxt(base_path + 'test.csv',delimiter=',', missing_values='-')
plt.figure()
plt.plot(range(250*10), data[range(250*10),1], '-')
plt.show()
```

I get this:

![figure_2](https://cloud.githubusercontent.com/assets/1282676/17260090/7f09acfa-559c-11e6-92cd-929d722d2d43.png)

If we directly compare the first lead from python (left) and using the shell (right):

Python (incorrect) | Shell (correct)
--- | ---
28.720 | -0.011
28.723 | -0.008
0.006 | 0.006
0.024 | 0.024
0.046 | 0.046
0.068 | 0.068
0.090 | 0.090
0.111 | 0.111
0.135 | 0.135
0.165 | 0.165

Looks like maybe the python package has underflow for negative values? Here's the header file:

```
v102s 4 250 75000
v102s.dat 212 2281/mV 0 0 -26 -9286 0 II
v102s.dat 212 1856/mV 0 0 340 2647 0 V
v102s.dat 212 1250/NU 0 0 -46 -11021 0 PLETH
v102s.dat 212 38880/NU 0 0 339 12236 0 RESP
```

**Comment by cx1111** [comment]
Yea you're right, I didn't convert the array to a signed type before adjusting for two's complement form. Funny how I had a unit test for fmt 212 but coincidentally all the values were +ve. 

Thanks
