### ISSUE TITLE
gqrs doesn't work

### ISSUE THREAD

**Issue by jscofi** [MIT-LCP/wfdb-python#113]
```
~/python/env/lib/python3.5/site-packages/wfdb/processing/qrs.py in sm(self, at_t)
    851                     smtlj = self.at(smt - j)
    852                     v += int(smtpj + smtlj)
--> 853                 self.smv_put(smt, (v << 1) + self.at(smt + j+1) + self.at(smt - j-1) - \
    854                              self.adc_zero * (smdt << 2))
    855 

UnboundLocalError: local variable 'j' referenced before assignment
```

**Comment by Dubrzr** [comment]
Hi,

Can you please provide an extract of the code that raised that error so that we can replicate it and fix it?

Thank you!

**Comment by DeepakSinghRawat** [comment]
@Dubrzr This is happening for me also. You can reproduce it by running ``# Demo 19 - Use the gqrs detection algorithm and correct the peaks`` cell in the demo.ipynb. It happens when smdt is 1. In that case the following block is not executed and j is not assigned.
``  for j in range(1, smdt):
                    smtpj = self.at(smt + j)
                    smtlj = self.at(smt - j)
                    v += int(smtpj + smtlj)
``

**Comment by cx1111** [comment]
I can't get that error on demo 19. It gives me smdt=6 for both python2.7 and 3.5.

In the `Conf` class, it gives a warning if smdt is 1. Perhaps I'll just make it fail then when fs is too small.
