### ISSUE TITLE
Suggestions for loading physiobank data

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/wfdb-python#12]
```python
import numpy as np
import urllib
targeturl="http://physionet.org/physiobank/database/macecgdb/test01_00s.dat"

hr=urllib.urlopen(targeturl) # The returned object is of type 'http.client.HTTPResponse'
content = hr.read() # This is a bytes object
content=np.array(list(content))
```

So right now the solution I have found to read physiobank data is to use the urlib package to return an HTTPResponse object for the read file. Then I use the read() method to extract a bytes object from it, which essentially gives me all the data in unsigned 1 byte format. This is ok but requires more processing for all the format types, as opposed to something like numpy.fromfile() where you can specify the format and gives you a numpy array directly. 

I've had a look at this doc page https://docs.python.org/3/library/http.client.html#http.client.HTTPResponse and tried to call `help(HR.read)` but I don't see a faster method than to read everything in 1 byte blocks, convert to a list, and then to a numpy array, and then to do calculations. If anyone knows of a more efficient method please let me know.

**Comment by tompollard** [comment]
Could you save the file locally, and then use `np.fromfile()`? e.g.

```python
import numpy as np
import urllib

targeturl = "http://physionet.org/physiobank/database/macecgdb/test01_00s.dat"

urllib.urlretrieve (targeturl, "test.dat")
data = np.fromfile("test.dat")
```

**Comment by cx1111** [comment]
Good idea! I could always add an option to delete the file after it is read too. 

Thanks.

**Comment by alistairewj** [comment]
Do the c tools have the concept of a cache/local folder where data is
downloaded to, or do they read directly from the website each time?
