### ISSUE TITLE
Get TypeError('sampto must be an integer') for some entries

### ISSUE THREAD

**Issue by steph409** [MIT-LCP/wfdb-python#121]
Hi :) 
I checked in the issues but I didn't find one that describes this: 
For some entries(~500) I get an TypeError: 

Minimal example: 
`entry = 'p00/p001190/p001190-2196-03-06-05-26n'`
 `wfdb.rdsamp(entry)`

It says: TypeError: sampto must be an integer

I use wfdb version 2.0.5. 

Best regards, 
Stephi

**Comment by cx1111** [comment]
Thanks. You can now download 2.1.1 which fixes it.

**Comment by steph409** [comment]
hi, I tried it and it works now, thanks :)
