### ISSUE TITLE
How to read a *.scp file with rdsamp?

### ISSUE THREAD

**Issue by TobyatLarge** [MIT-LCP/wfdb-python#122]
Wondering does rdsamp support reading *.scp or *.res file?

I got those files from holter monitor...

Having a difficult time reading them into python now @_@ 

Thanks for help!

ps--
a typical line from *.scp file looks like this in sublime (with view.encoding() = 'hexadecimal'

00b1 0296 006f 0113 0057 004f 00c1 00a3

**Comment by cx1111** [comment]
I did find this for the original wfdb c package: https://physionet.org/physiotools/wag/parses-1.htm
