### ISSUE TITLE
A question about correct_peaks()

### ISSUE THREAD

**Issue by Allenlzcoder** [MIT-LCP/wfdb-python#124]
Well, recently I meet a problem when using gqrs_detect() & correct_peaks() 
to get a peak position exactly on the R peak and then calculate the heart rate. I find that if the amplitude of T wave is relatively high (In extreme cases, the amplitude of T wave is almost as high as R wave) or the heart rate is relatively slow(under 60/min), the result of correct_peaks() always consider some T peak as R peak by error.
       Em....I don't konw how to upload the picture.Is there any good solutions to solve the problem?
Thank you!

**Comment by Dubrzr** [comment]
Maybe you could try to reduce the search_radius parameter of the correct_peak function.
Did you checked what was the result of gqrs_detect before correct_peak? Maybe the problem is that gqrs_detect find wrong R peaks?

**Comment by Dubrzr** [comment]
You could try @cx1111's own QRS detector based on Pan&Tompkins included in this package  http://wfdb.readthedocs.io/en/latest/processing.html#wfdb.processing.XQRS

**Comment by Allenlzcoder** [comment]
Well, thanks to your reply sincerely! Due to there is no physical value interface in XQRS class, I want to transfer my physical value to digital value .Is there a transfer function in this packge?
Thank you again!

**Comment by Dubrzr** [comment]
I think http://wfdb.readthedocs.io/en/latest/io.html#wfdb.io.Record.adc is what you're looking for, right @cx1111?

**Comment by Allenlzcoder** [comment]
well,in order to convert the physical values to digital values in gqrs_detect() function in the file of qrs.py, there is a piece of code as follows:
`    if sig is not None:
        record = Record(p_signal=sig.reshape([-1,1]), fmt=['24'])
        record.set_d_features(do_adc=True)
        d_sig = record.d_signal[:,0]
        adc_zero = 0
        adc_gain = record.adc_gain[0]`
        Can I use the same way to convert data format? Are they the same working principles?
        Thanks!

**Comment by cx1111** [comment]
xqrs actually uses physical values. Regarding adc dac and such, I will be clarifying it in the future. There's an issue #103 which tracks it.

**Comment by zahrafarook** [comment]
Can you explain this piece of code, please
# Correct the peaks shifting them to local maxima
min_bpm = 20
max_bpm = 230
#min_gap = record.fs * 60 / min_bpm
# Use the maximum possible bpm as the search radius
search_radius = int(record.fs * 60 / max_bpm)
corrected_peak_inds = processing.peaks.correct_peaks(record.p_signal[:,0], 
                                                     peak_inds=qrs_inds,
                                                     search_radius=search_radius, 
                                                     smooth_window_size=150)
