### ISSUE TITLE
Passing a  different URL instead of Physionet database

### ISSUE THREAD

**Issue by achuthpv** [MIT-LCP/wfdb-python#125]
It is seen in [_download.py_](https://github.com/MIT-LCP/wfdb-python/blob/master/wfdb/io/download.py) that URL is hard coded to [Physionet database](http://physionet.org/physiobank/database/). Is there any method available for passing a different URL to fetch data from instead of Physionet database URL? The feature I am looking for is similar to [_setwfdb_](https://www.physionet.org/physiotools/wag/setwfd-1.htm) found in WFDB software package where any desired URL can be added in **WFDB** path. The package can use this URL to download the data. 
I am having a use case where the data required (in wfdb format) resides on a different server and we wanted to stream the data instead of downloading it completely and it storing it locally.

I have already created a fork and a [branch](https://github.com/MIT-LCP/wfdb-python/compare/master...achuthpv:using_env_WFDB_PATH_for_URL) . This is the format which I have in my mind.
Thanks

**Comment by cx1111** [comment]
You can call this now:
```
def set_db_index_url(db_index_url=PB_INDEX_URL):
    """
    Set the database index url to a custom value, to stream remote
    files from another location.

    Parameters
    ----------
    db_index_url : str, optional
        The desired new database index url. Leave as default to reset
        to the physiobank index url.

    """
    config.db_index_url = db_index_url
```
