### ISSUE TITLE
io.rdrecord() fails when sampto is 'end'

### ISSUE THREAD

**Issue by atpage** [MIT-LCP/wfdb-python#129]
Calling `rdsamp()` or `rdrecord()` with `sampto='end'` replaces `sampto` with `sig_len` from the header, which may be `None`, causing `check_read_inputs()` to fail.  I have patched this locally in the case where `sig_len` is `None` by replacing `sig_len` with `filesize*8/bits_per_sample/n_sig`, where `bits_per_sample` is looked up in this dict keyed on `record.fmt`:

    bits_per_sample = {
        '8':    8,
        '16':  16,
        '24':  24,
        '32':  32,
        '61':  16,
        '80':   8,
        '160': 16,
        '212': 12,
        '310': 32.0/3,
        '311': 32.0/3,
    }

**Comment by atpage** [comment]
Also, I saw the recently closed issues related to this, but I am already on 2.1.1.

**Comment by cx1111** [comment]
Do you have an example of a record with a signal length?

**Comment by atpage** [comment]
I don't know if there are any examples on Physionet, but it is not a required field in the header. [1]

I do have files (which I cannot share) that have been exported to MIT format by an ECG device manufacturer, and the first line of the header is

    <name> <channels> <sample rate>

i.e. signal length is omitted.  That's how I encountered the problem.

[1] https://www.physionet.org/physiotools/wag/header-5.htm (number of samples per signal)
