### ISSUE TITLE
Why the result of _learn_init_params()  in XQRS always prints "Failed to......" when detecting qrs?

### ISSUE THREAD

**Issue by Allenlzcoder** [MIT-LCP/wfdb-python#130]
The permance of xqrs is good based on mitdb. But I find that the result of _learn_init_params()  in XQRS always prints "Failed to......". How make _learn_init_params() conduct successfully?
Thanks for your reply~

**Comment by cx1111** [comment]
The code is very well documented. I describe exactly how every step works. You should read it.

I actually commented in the function that I am convoluting the ricker wavelet with the ecg signal without taking the square or magnitude, so inverse ecgs will not be captured well. Solutions may be to take the square/magnitude, or to figure out the ecg direction via skew or something like that.

If you have ideas, feel free to contribute them.

**Comment by cx1111** [comment]
I indexed a variable wrong during learning so it didn't even go through the correct peaks. Either way, I'll be making some improvements to the function.
