### ISSUE TITLE
Reading only a specific channel

### ISSUE THREAD

**Issue by jbehar** [MIT-LCP/wfdb-python#132]
Hi,
I see that as an option to rdsamp we can input the channel number. However, is there a way to read only the channels of type e.g. 'ECG'/'ecg' or 'PLET' as labelled in the header?
Cheers,
Joachim

**Comment by jbehar** [comment]
Any feedback on whether or not this is feasible? :)
Cheers

**Comment by cx1111** [comment]
I'll add this option in a few days.

I assume if the channels are not present, you would prefer a Record object with an empty numpy array returned rather than an exception raised?

**Comment by jbehar** [comment]
Yes that would be best so that I can test easily if there is ECG data in a given record or not.
It's perhaps a good idea to be able to pass as an argument a list like {'ECG','ecg','PLET'} that would return all the signals with one of the labels in the list. This is particularly useful if the naming of the channel changes from a database to another for a given quantity (e.g. 'BP' or 'bp' or 'blood pressure').
Thanks

**Comment by cx1111** [comment]
So then let's say you read a record with channels: `['pleth', 'ecg']`, with the new argument set: `channel_names=['ecg', 'pleth', 'resp']`

You would expect an M x 2 array with channels corresponding to `['pleth', 'ecg']` right?

**Comment by jbehar** [comment]
Yes that would work nicely

**Comment by cx1111** [comment]
I've added the parameter.

**Comment by jbehar** [comment]
Thanks! I will test it this week or the next.
