### ISSUE TITLE
Installation got broken

### ISSUE THREAD

**Issue by GillesVandewiele** [MIT-LCP/wfdb-python#135]
Hello, the latest commit broke the installation in python3

```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-0aqbj3nl/wfdb/setup.py", line 19, in <module>
        __version__ = f.read().split()[-1].strip("'")
    TypeError: Type str doesn't support the buffer API
```

Fixed by changing https://github.com/MIT-LCP/wfdb-python/blob/master/setup.py#L19 to

`__version__ = str(f.read().split()[-1].strip(b"\'"))`

--> But definitely not sure if this is the best fix ;)

**Comment by cx1111** [comment]
I don't support python 3.4, but I even tried it on 3.4.2 and get a str object.
