### ISSUE TITLE
Format 24 not supported

### ISSUE THREAD

**Issue by biggates** [MIT-LCP/wfdb-python#138]
According to [signal-5](https://physionet.org/physiotools/wag/signal-5.htm) and `DATA_LOAD_TYPES` in `_signal.py`, `Format 24` is already considered.

```python
# Numpy dtypes used to load dat files of each format.
DATA_LOAD_TYPES = {'8': '<i1', '16': '<i2', '24': '<i3', '32': '<i4',
                   '61': '>i2', '80': '<u1', '160': '<u2', '212': '<u1',
                   '310': '<u1', '311': '<u1'}
```

However, `'<i3'` is not supported in python:

```python
>>> import numpy
>>> numpy.dtype('<i2')
dtype('int16')
>>> numpy.dtype('<i4')
dtype('int32')
>>> numpy.dtype('<i3')
Traceback (most recent call ast):
  File "<stdin>", line 1, in <module>
TypeError: data type "<i3" not understood
```

Of course this is not a big problem, as Format 24 is rarely used.

To better reproduce this problem:

File `test.hea`:
```
test 2 150 21919 09:13:44 04/06/2018
test.dat 24 0(1)/mV 8 0 0 0 0 ECG
test.dat 24 0(1)/mV 8 0 0 0 0 PLETH
```
File `test.dat`: 
```
(An empty file is enough, as it is not read)
```

The whole stacktrace:

```
>>> record = wfdb.rdrecord('test/test')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "...\wfdb\io\record.py", line 1232, in rdrecord
    ignore_skew)
  File "...\wfdb\io\_signal.py", line 876, in _rd_segment
    smooth_frames)[:, r_w_channel[fn]]
  File "...\wfdb\io\_signal.py", line 968, in _rd_dat_signals
    n_read_samples)
  File "...\wfdb\io\_signal.py", line 1226, in _rd_dat_file
    sig_data = np.fromfile(fp, dtype=np.dtype(DATA_LOAD_TYPES[fmt]),
TypeError: data type "<i3" not understood
```

**Comment by Lucas-Mc** [comment]
@biggates Thanks for the response and sorry for the delay we have been shifting focus between this project, MIMIC, and Physionet! 

I think I have a solution for this issue but I am struggling to find a suitable example to test it. Do you happen to have a set of Format 24 data you were planning to use? I was also considering having it raise an exception for now until the appropriate testing can be done. Thanks again!

**Comment by Lucas-Mc** [comment]
@biggates Nevermind, just found some here!! https://physionet.org/content/earndb/1.0.0/raw/N8/n8_evoked_raw_95_F1_R9.hea

**Comment by Lucas-Mc** [comment]
@biggates Solved! Feel free to test it out, I did some testing of my own but it may not work for all cases so help is always appreciated! Thanks!
