### ISSUE TITLE
The time between Waveform record and MIMIC-III Clinical Database can not be completely matched

### ISSUE THREAD

**Issue by liuxiaoliXRZS** [MIT-LCP/wfdb-python#147]
Hi Alistair, I found that the time between Waveform record and MIMIC-III Clinical Database can not be completely matched. For example, the subject_id of  125, 298, 333, 422, 818, 1030, 1174, 1192, 1337, 1457. Why and how to solve it? Thanks! @alistairewj

**Comment by alistairewj** [comment]
Could you be more specific on how it could not be matched? Is it that you have a waveform record but no corresponding clinical record that overlaps?

**Comment by xiaoliliuxrzs** [comment]
For example, subject_id = 818, a file recording starttime was 2168-03-18-12-04 in MIMIC-III Waveform Database. While the patient's intime of icu was 2157-08-10-18-03-00 in MIMIC Critical Care Database. The interval between them was too long and I can not match the time between them.
