### ISSUE TITLE
Unexpected behaviour for wrann when passing a different aux_note argument

### ISSUE THREAD

**Issue by Gabriel-Azevedo-Ferreira** [MIT-LCP/wfdb-python#149]
If aux_note is a ndarray (and not a list, as specified in the documentation), we do not receive any error message, but obtain a Aux field with problems in format.

Example:

`aux = ['(NSR', '']`
`wfdb.wrann(output_name, extension, sample=sample, symbol=symbol, aux_note=[a for a in aux])`
`wfdb.rdann(output_name, extension).aux_note`

outputs:
`
['(NSR', '']
`
but
`aux = np.array(['(NSR', ''])`
`wfdb.wrann(output_name, extension, sample=sample, symbol=symbol, aux_note=[a for a in aux])`
`wfdb.rdann(output_name, extension).aux_note`
outputs:
`
['(NSR', 'None']
`

which is an unexpected behaviour

**Comment by Lucas-Mc** [comment]
I can't find the exact change that fixed this issue, but I ran it locally and could not re-create. Possibly linked to here? 

https://github.com/MIT-LCP/wfdb-python/blob/f69c7df7ac4ed3a6f6262474225bd976bcb115f6/wfdb/io/annotation.py#L769-L770
