### ISSUE TITLE
Plotting different annotation symbols

### ISSUE THREAD

**Issue by pani3610** [MIT-LCP/wfdb-python#152]
I want to plot different annotation symbols for different  beat events like given in https://physionet.org/physiobank/annotations.shtml

When i use plot_items(..,ann_style=[<any symbol>],..), i get the same symbol for all annotations regardless of type.

PS: I apologize in advance if a solution already exists. I could not find it so putting it here. I am a beginner, here to learn.
![figure_2](https://user-images.githubusercontent.com/24316007/49865897-2b1ae880-fe2c-11e8-9410-1691229afde5.png)

**Comment by Gabriel-Azevedo-Ferreira** [comment]
You could provide the fields "ann_sam" (a list with the samples) and "ann_sym" (a list with the symbols) to the function plot_items, which will plot the symbols as well.

Alternativelly you could use the following structure

```
import wfdb
record = wfdb.rdrecord('../../database/mitdb/100')
ann = wfdb.rdann('../../database/mitdb/100', 'atr')
wfdb.plot_wfdb(record,ann,plot_sym=True,time_units='seconds')
```

Setting plot_sym to True well enable you to plot the symbols.
(Behind the scenes it is basically calling plot_items, and providing the fields "ann_sam" and "ann_sym")
