### ISSUE TITLE
Is it a bug that rdrecord() load signal always from '0' ?

### ISSUE THREAD

**Issue by vortune** [MIT-LCP/wfdb-python#155]
I try to load the record and annotation of a ecg, and plot them out :

`>>> rec = wfdb.rdrecord('100', sampfrom=3000, sampto=6000)`
`>>> ann = wfdb.rdann('100', 'atr', sampfrom=3000, sampto=6000)`
`>>> wfdb.plot_wfdb(record=rec, annotation=ann, plot_sym=True)`

I got the error:

`
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robin/.local/lib/python3.6/site-packages/wfdb/plot/plot.py", line 414, in plot_wfdb
    figsize=figsize, return_fig=return_fig)
  File "/home/robin/.local/lib/python3.6/site-packages/wfdb/plot/plot.py", line 111, in plot_items
    time_units, ann_style, axes)
  File "/home/robin/.local/lib/python3.6/site-packages/wfdb/plot/plot.py", line 204, in plot_annotation
    y = signal[ann_samp[ch], ch]
IndexError: index 3282 is out of bounds for axis 0 with size 3000
`

I Inspect objects of record and annotation with plotting out them individually:

`>>> wfdb.plot_wfdb(record=rec)`
`>>> wfdb.plot_wfdb(annotation=ann)`

I found the signal window of record object is in range of `0~3000`, is it my fault or a bug of `rdrecord()`?

But the annotation object has a correct signal window of `3000~6000`.

The package of WFDB information:

`$ pip3 show wfdb`
Name: wfdb
Version: 2.2.1
Summary: The WFDB Python Toolbox
Home-page: https://github.com/MIT-LCP/wfdb-python
Author: The Laboratory for Computational Physiology
Author-email: support@physionet.org
License: MIT
Location: /home/robin/.local/lib/python3.6/site-packages
Requires: matplotlib, sklearn, pandas, numpy, requests, nose, scipy

![annotation_100](https://user-images.githubusercontent.com/25348764/50464461-dd75b280-09cb-11e9-86dd-7b3af4ee19f0.png)
![record_100](https://user-images.githubusercontent.com/25348764/50464463-de0e4900-09cb-11e9-8abc-ff8b6dc3fda7.png)

**Comment by cx1111** [comment]
It's not a bug. rdrecord loads a the signal as a numpy array with no time dimension.

rdann has a floor_samp input argument or something like that to help with this alignment.

**Comment by vortune** [comment]
Thanks, Dear Mr. Xie :


I am a newbie to wfdb-python. Are there any example codes to demonstrate how to align the record and annotation ?


Best regard !




--

罗峥嵘（Robin Luo）
--------------------------------------------------------------
CELLPHONE:   +86 135 8032 6828
TEL:                  +86 20 6288 0399
EMAIL:             vortune@163.com
WEB:                http://www.warickmedical.com


广州沃里医疗科技有限公司
地址：             广州市萝岗区科学城科学大道182号创新大厦C2-208室
邮政编号：       510663




Guangzhou Warick Medical Technology Co., LTD
ADDRESS:      Room 208, Building C2, No.182 of Kexue Avenue,
                       Science Town of Luogang District, 
                       Guangzhou, Guangdong, China
POSTCODE:    510663



At 2018-12-28 01:06:25, "Chen Xie" <notifications@github.com> wrote:


It's not a bug. rdrecord loads a the signal as a numpy array with no time dimension.

rdann has a floor_samp input argument or something like that to help with this alignment.

**Comment by vortune** [comment]
Thanks, Xie :


I solved the alignment of record and annotation with setting the parameter of rdann() to 'True'.

Best regard.



--

罗峥嵘（Robin Luo）
--------------------------------------------------------------
CELLPHONE:   +86 135 8032 6828
TEL:                  +86 20 6288 0399
EMAIL:             vortune@163.com
WEB:                http://www.warickmedical.com


广州沃里医疗科技有限公司
地址：             广州市萝岗区科学城科学大道182号创新大厦C2-208室
邮政编号：       510663




Guangzhou Warick Medical Technology Co., LTD
ADDRESS:      Room 208, Building C2, No.182 of Kexue Avenue,
                       Science Town of Luogang District, 
                       Guangzhou, Guangdong, China
POSTCODE:    510663



在 2018-12-28 01:06:26，"Chen Xie" <notifications@github.com> 写道：


Closed #155.
