### ISSUE TITLE
plot_wfdb() times don't math for annotation and record

### ISSUE THREAD

**Issue by elliot-brown** [MIT-LCP/wfdb-python#162]
The following code either has the annotations in the incorrect place or results in an IndexError, depending on the specific choices of _sampfrom_ and _sampto_:
```
record = wfdb.rdrecord('mitdb/100', sampfrom=360, sampto=1080)    
annotation = wfdb.rdann('mitdb/100', 'atr', sampfrom=360, sampto=1080)
wfdb.plot_wfdb(record=record, annotation=annotation, time_units='seconds')
```
I believe the issue is that when plotting the record only, the x-axis begins at 0 regardless. But the x-axis of the annotation-only plot begins at the corresponding time.  In this example, 
```
wfdb.plot_wfdb(record=record, annotation=None, time_units='seconds')
```
plots from 0 to 2 seconds, whereas
```
wfdb.plot_wfdb(record=None, annotation=annotation, time_units='seconds')
```
plots from 1 to 3 seconds.

So when trying to plot both,
```
wfdb.plot_wfdb(record=record, annotation=annotation, time_units='seconds')
```
you typically get an IndexError (because the annotation index in out of bounds) or sometimes a graph with annotations that don't line up.

I'm not sure what the best solution is. It makes sense that the annotations are associated with a sample number. Maybe the record should be too?

**Comment by Lucas-Mc** [comment]
Hey @elliot-brown, I am going to try and work on this now. I have the following plot to share:
![Test_Plot_Rec_Ann](https://user-images.githubusercontent.com/39505798/81211868-02a40900-8fa2-11ea-9d14-edcc23a9ae6d.png)
This is what it looks like if you remove the final annotation generating the error, confirming your suspicions about mis-aligned indexing. Code to duplicate:
```
import wfdb
record = wfdb.rdrecord('mitdb/100', sampfrom=360, sampto=1080)    
annotation = wfdb.rdann('mitdb/100', 'atr', sampfrom=360, sampto=1080)
annotation.sample = np.array([370,662])
annotation.subtype = np.array([0,0])
annotation.chan = np.array([0,0])
annotation.num = np.array([0,0])
annotation.aux_note = np.array(['',''])
wfdb.plot_wfdb(record=record, annotation=annotation, time_units='seconds')
```

**Comment by Lucas-Mc** [comment]
Update: The code works if you make the following edit:
`annotation = wfdb.rdann('mitdb/100', 'atr', sampfrom=360, sampto=1080, shift_samps=True)`
This then generates the following correct plot:
![Correct_Rec_Ann_Plot](https://user-images.githubusercontent.com/39505798/81215338-3170ae00-8fa7-11ea-8a6e-034589a4c469.png)
It appears like the annotations aren't being shifted over unless that parameter is set to `True` although it should if the `sampfrom` is greater than 0 and the record is being plotted with it. Working on how to find the best solution.

**Comment by Lucas-Mc** [comment]
I'm making a pull request now and decided to leave the functionality as it is but add a more descriptive error message in place of the current `IndexError` default message. Instead, I specifically tell the user to utilize the `shift_samps=True` parameter when importing the annotation data. Hopefully this helps!
