### ISSUE TITLE
easify xlabel adaption for plotting

### ISSUE THREAD

**Issue by matu3ba** [MIT-LCP/wfdb-python#163]
Why is there no option to set the x-axis via `xlabel` for `plot_items` ?
Trying to adapt the figure via
ylabels=['mV']
fig = plot_items(signal=signal, ylabel=ylabels, return_fig=True)
fig.xlabel = 'test'
fig.savefig('plot' + str(plotcount) + '.eps', format='eps')
works without the change of xlabel.
https://stackoverflow.com/questions/12444716/how-do-i-set-the-figure-title-and-axes-labels-font-size-in-matplotlib

Am I missing anything or is there any technical reason why to not give the option to overwrite the axis?
You could also return the axis in addition to the figure to make adaptions possible.
The saving of .eps format upon dialog may be broken as well, but that is not big deal.

**Comment by Dubrzr** [comment]
Hi matu3ba, 
Don't hesitate to make pull requests if you think something is wrong/missing.
Julien
