### ISSUE TITLE
HTTPError: 404 Client Error

### ISSUE THREAD

**Issue by rafaelprr6** [MIT-LCP/wfdb-python#166]

**Comment by rafaelprr6** [comment]
I am trying to download a Pysionet database but it is returning this error:

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://physionet.org/physiobank/database/mitdb

**Comment by alistairewj** [comment]
It's up, but you need to add a trailing slash:
https://physionet.org/physiobank/database/mitdb/

We'll look towards fixing this in the near future.

>

**Comment by rafaelprr6** [comment]
Ok, thanks for the help.
