### ISSUE TITLE
No .hea file when pulling from website with 'rdsamp'

### ISSUE THREAD

**Issue by jonmart0304** [MIT-LCP/wfdb-python#169]
I am using wfdb.rdsamp('s0306lre', pb_dir='ptdb/patient104/') to access data from the physionet website.  However, I'm getting the following error:

requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://physion
et.org/physiobank/database/ptdb/patient104/s0306lre.hea

I know the .hea file is there but it does not download when clicked. You have to copy the contents of the file and paste it to a new file in your local directory yourself. 

I'm trying to avoid manually pulling a bunch of data by hand.
Any help is greatly appreciated.

**Comment by lkjell** [comment]
It appears that the database name is wrong. The only database name that is similar to the one you write is pt**b**db not ptdb. https://physionet.org/physiobank/database/ptbdb/
