### ISSUE TITLE
How to easily generate wfdb record from dataframe?

### ISSUE THREAD

**Issue by nimasubra** [MIT-LCP/wfdb-python#173]
Forgive my ignorance, I am just a clinician learning to code for a predictive health modeling project and I am exploring whether I can use this package to easily calculate QRS duration for ECG data taken from wearable devices. 

My data is in a pandas dataframe. Is there any method for generating a WFDB-compatible record directly from a dataframe using Python? Alternatively, do I have to download the WFDB Software Package to create the records from CSV?

**Comment by nimasubra** [comment]
Nevermind, I figured out it takes np arrays! -_-'

Also I don't think I will be able to calculate QRS durations because there is no wqrs which is the Physiotoolkit I need.

**Comment by Lucas-Mc** [comment]
@nimasubra I'll add implementing the WQRS function as a priority to the list of new content on the way! Thanks so much for the comment!
