### ISSUE TITLE
Recreating WFDB command in python

### ISSUE THREAD

**Issue by steweiss** [MIT-LCP/wfdb-python#178]
Hi,
I want to recreate the following shell command of  the original WFDB with this package:
wrsamp -F 200 -i foo.csv -o foo -s, 0

It will create from an .csv header files which can then be annotated by 
echo '# <age>: 35  <sex>: M  <diagnoses>: (none)  <medications>: (none)' | cat - foo.csv > temp && mv temp foo.csv
to be ready for edf (by python convert_ediagnostic_2_wfdb.py)

Sadly I want it platform-independent and the original WFDB is not so strong here, can you help to recreate, bc. I do not see how this is intended in your package?

**Comment by Lucas-Mc** [comment]
I need to think about this more but I know that this is how you can recreate the `rdsamp` CSV output:
```
import wfdb
import numpy as np

rec = wfdb.rdrecord('sample-data/100', physical=False)
output_array = np.hstack((np.expand_dims(np.arange(0,rec.sig_len), axis=1), rec.d_signal))
np.savetxt('foo.csv', output_array, delimiter=',', fmt='%i')
```
