### ISSUE TITLE
Running time of xqrs looks not linear

### ISSUE THREAD

**Issue by hsd1503** [MIT-LCP/wfdb-python#180]
Is there anything special of xqrs algorithm that lead to this? I found the running time vs length looks not linear. Thanks!

![image](https://user-images.githubusercontent.com/7302031/67996522-12731700-fc26-11e9-94c2-0291c2ccd9f8.png)

The testing code:
```
import wfdb
import numpy as np
from wfdb.processing import xqrs_detect
import time
from matplotlib import pyplot as plt

signals, fields = wfdb.rdsamp('somefile_for_MIMIC_waveform', channel_names=['II'])
signals = np.nan_to_num(signals[:,0])

chunck_list = list(np.arange(1e3, 1e4, 1e3)) + list(np.arange(1e4, 1e5, 1e4))
t_list = []
for chunk in chunck_list:
    t1 = time.time()
    tmp_qrs_inds = xqrs_detect(sig=signals[:int(chunk)], fs=fields['fs'], verbose=False)
    t2 = time.time()
    t_list.append(t2-t1)
    print('time {0}s'.format(t2-t1))

plt.plot(chunck_list, t_list)
plt.title('running time of xqrs')
plt.xlabel('length')
plt.ylabel('time/sec')
plt.savefig('wfdb_time.png')
```

**Comment by Lucas-Mc** [comment]
Hello, thanks for submitting this observation! I have tried to recreate this plot but cannot find a dataset that matches the non-linear growth in runtime. What is the dataset that you used for this specific plot? Most of my plots have been bouncing around up and down regardless of length and the magnitudes are nowhere near the 10 seconds you are seeing.

**Comment by hsd1503** [comment]
Hello, thanks for your reply. I was using the mimic-iii waveform database at that time. During the months, I keep updating wfdb-python, but not tested that code again. Now I just tested and everything is working good (nearly linear running time)! Thanks for your time. Hope you are safe and healthy!
