### ISSUE TITLE
Install wfdb in Raspberry Pi4

### ISSUE THREAD

**Issue by MishalJasmine** [MIT-LCP/wfdb-python#184]
Hi, I am trying to install the `wfdb` package in `Rasberry Pi4`. Even though the installation goes till the end, while importing the package in the python script, it gives the error                                 
`Traceback (most recent call last):`
 `File "MIT_data.py", line 11, in <module>`
 ` import wfdb`
`ImportError: No module named wfdb`

Can you please tell me help me with this? I also restarted the terminal.

**Comment by alistairewj** [comment]
Seems like it didn't install properly - perhaps you installed it in a different virtual environment or something like that.

**Comment by MishalJasmine** [comment]
@alistairewj , I have done the installation from the terminal using the command `pip install wfdb` and no virtual environment was used. I have already installed wfdb package in Linux using the same command. If u see the installing procedure, it collects the other packages line pandas, scipy and so on but not wfdb. It does not say `requirement already satisfied` for wfdb.

![2019-12-16-103623_1920x1080_scrot](https://user-images.githubusercontent.com/51846137/70880884-adfef200-1ff0-11ea-8ee0-d7dddf443b8d.png)

**Comment by alistairewj** [comment]
It looks like you are missing some operating system level libraries required for scipy, which causes the scipy installation to fail. wfdb requires scipy so it subsequently fails.

Try installing the necessary libraries (OpenBLAS and LAPACK) before installing wfdb.

**Comment by MishalJasmine** [comment]
@alistairewj , thank you for the suggestion.  `sudo apt-get install python-numpy python-scipy' on using this command the scipy package was installed. Then `pip install wfdb` was successful. Its always better to install the packages using `apt-get` solves a lot of problems.

**Comment by alistairewj** [comment]
Great!
