### ISSUE TITLE
TypeError: data type " in rerun the demo codes

### ISSUE THREAD

**Issue by lightis-tian** [MIT-LCP/wfdb-python#198]
I just run the demo.py, use the following codes:
record2 = wfdb.rdrecord('a103l', pb_dir='challenge/2015/training/'), and then give me that type error:
`----> 1 signals2, fields2 = wfdb.rdsamp('s0010_re', channels=[14, 0, 5, 10], sampfrom=100, sampto=15000, pb_dir='ptbdb/patient001/')

E:\hetian\anaconda\installfolder\envs\hetian_tf2\lib\site-packages\wfdb\io\record.py in rdsamp(record_name, sampfrom, sampto, channels, pb_dir, channel_names, warn_empty)
   1392                       sampto=sampto, channels=channels, physical=True,
   1393                       pb_dir=pb_dir, m2s=True, channel_names=channel_names,
-> 1394                       warn_empty=warn_empty)
   1395 
   1396     signals = record.p_signal

E:\hetian\anaconda\installfolder\envs\hetian_tf2\lib\site-packages\wfdb\io\record.py in rdrecord(record_name, sampfrom, sampto, channels, physical, pb_dir, m2s, smooth_frames, ignore_skew, return_res, force_channels, channel_names, warn_empty)
   1230                                                   record.skew, sampfrom, sampto,
   1231                                                   channels, smooth_frames,
-> 1232                                                   ignore_skew)
   1233 
   1234             # Arrange/edit the object fields to reflect user channel

E:\hetian\anaconda\installfolder\envs\hetian_tf2\lib\site-packages\wfdb\io\_signal.py in _rd_segment(file_name, dir_name, pb_dir, fmt, n_sig, sig_len, byte_offset, samps_per_frame, skew, sampfrom, sampto, channels, smooth_frames, ignore_skew)
    874                 w_fmt[fn], len(datchannel[fn]), sig_len, w_byte_offset[fn],
    875                 w_samps_per_frame[fn], w_skew[fn], sampfrom, sampto,
--> 876                 smooth_frames)[:, r_w_channel[fn]]
    877 
    878     # Return each sample in signals with multiple samples/frame, without smoothing.

E:\hetian\anaconda\installfolder\envs\hetian_tf2\lib\site-packages\wfdb\io\_signal.py in _rd_dat_signals(file_name, dir_name, pb_dir, fmt, n_sig, sig_len, byte_offset, samps_per_frame, skew, sampfrom, sampto, smooth_frames)
    966     else:
    967         sig_data = _rd_dat_file(file_name, dir_name, pb_dir, fmt, start_byte,
--> 968                                  n_read_samples)
    969 
    970     # Finish processing the read data into proper samples if not already

E:\hetian\anaconda\installfolder\envs\hetian_tf2\lib\site-packages\wfdb\io\_signal.py in _rd_dat_file(file_name, dir_name, pb_dir, fmt, start_byte, n_samp)
   1243 
   1244         sig_data = download._stream_dat(file_name, pb_dir, byte_count,
-> 1245                                         start_byte, dtype_in)
   1246 
   1247     return sig_data

E:\hetian\anaconda\installfolder\envs\hetian_tf2\lib\site-packages\wfdb\io\download.py in _stream_dat(file_name, pb_dir, byte_count, start_byte, dtype)
    155 
    156     # Convert to numpy array
--> 157     if dtype == ':
    158         # Convert 24-bit to 16-bit then proceed
    159         temp_data = np.frombuffer(response.content, 'b').reshape(-1,3)[:,1:].flatten().view('i2')

TypeError: data type "`

how could i fix it?

**Comment by Lucas-Mc** [comment]
Hey @lightis-tian, thanks for the feedback! This is a known issue. Support for 24-bit signals has been stated for a while though its presence was limited which meant some bugs weren't being caught. A previous PR #193 fixed some of these issues but exposed more which should be solved very shortly when PR #200 is merged.
