### ISSUE TITLE
Failure reading Apnea-ECG database

### ISSUE THREAD

**Issue by hahnicity** [MIT-LCP/wfdb-python#208]
I've been looking into using the apnea-ecg dataset with the python wfdb wrapper but when I try to load a file using rdsamp I get an error message.

Code to reproduce:
```
import wfdb
wfdb.rdsamp('x01')
```
Here is the error message.
```
IndexError                                Traceback (most recent call last)
<ipython-input-3-b4071abcbb16> in <module>()
----> 1 wfdb.rdsamp('x01')
/home/greg/anaconda3/envs/deepards/lib/python2.7/site-packages/wfdb/io/record.pyc in rdsamp(record_name, sampfrom, sampto, channels, pb_dir, channel_names, warn_empty)
   1392                       sampto=sampto, channels=channels, physical=True,
   1393                       pb_dir=pb_dir, m2s=True, channel_names=channel_names,
-> 1394                       warn_empty=warn_empty)
   1395
   1396     signals = record.p_signal
/home/greg/anaconda3/envs/deepards/lib/python2.7/site-packages/wfdb/io/record.pyc in rdrecord(record_name, sampfrom, sampto, channels, physical, pb_dir, m2s, smooth_frames, ignore_skew, return_res, force_channels, channel_names, warn_empty)
   1152
   1153     # Read the header fields
-> 1154     record = rdheader(record_name, pb_dir=pb_dir, rd_segments=False)
   1155
   1156     # Set defaults for sampto and channels input variables
/home/greg/anaconda3/envs/deepards/lib/python2.7/site-packages/wfdb/io/record.pyc in rdheader(record_name, pb_dir, rd_segments)
    992
    993     # Get fields from record line
--> 994     record_fields = _header._parse_record_line(header_lines[0])
    995
    996     # Single segment header - Process signal specification lines
/home/greg/anaconda3/envs/deepards/lib/python2.7/site-packages/wfdb/io/_header.py in _parse_record_line(record_line)
    745      record_fields['counter_freq'], record_fields['base_counter'],
    746      record_fields['sig_len'], record_fields['base_time'],
--> 747      record_fields['base_date']) = re.findall(_rx_record, record_line)[0]
    748
    749     for field in RECORD_SPECS.index:
IndexError: list index out of range
```

I've tried to track down the problem and it seems to be originating in the .hea files. Apparently the python software is trying to parse extensive information from the first line of the file, but the first line is just an XML "<DOCTYPE>" header. So there's really no information to parse, and the software fails. 

WFDB version: 2.2.1

**Comment by Lucas-Mc** [comment]
Hey @hahnicity , I just tried to reproduce this issue on WFDB version 2.2.1 and could not get the same error as you. How did you download the files? I just downloaded them directly from Physionet. These files shouldn't have any kind of XML header to begin with so it sounds like it's a problem with the file. Maybe try to download directly from Physionet to see if this fixes the issue? Let me know what you get! Thanks!

**Comment by hahnicity** [comment]
Hi @Lucas-Mc thanks for the fast reply. Yes I have downloaded the files onto my own computer. I downloaded them as a zip file and then unpackaged them on my computer. Then I renamed the directory afterwards. I have redownloaded the dataset via zip and via wget, and I too cannot reproduce the error. Thanks for your time
