### ISSUE TITLE
Default behaviour for locating and downloading files in rdsamp

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/wfdb-python#21]
The rdsamp locate-and-download-file behavior could be explicitly set with arguments, rather than having a separate config file. 

Sensible behaviour might be:

- rdsamp requires the path to the file to be specified as an argument.
- rdsamp saves the data to the current working directory (`os.cwd`) unless a download directory is specified as an argument.

**Comment by cx1111** [comment]
`def rdsamp(recordname, dldir=[]):
    
    if dldir:
        downloadrecordfiles(physiobank/recordname, dldir)
`
That seems efficient, adding only 1 argument. But then how would you set the default dl dir to cwd?
