### ISSUE TITLE
Wish list for WFDB functions

### ISSUE THREAD

**Issue by tompollard** [MIT-LCP/wfdb-python#23]
A list of functions available in the original WFDB package is at:
https://physionet.org/physiotools/wag/wag.htm

Which other of these functions would it be helpful to implement?

**Comment by alistairewj** [comment]
`wrann` feels like it would be the most useful at the moment as it would facilitate coding PhysioNet Challenge entries entirely in Python.

**Comment by tompollard** [comment]
Thanks Alistair - I have created a development branch for wrann: https://github.com/MIT-LCP/wfdb-python/tree/wrann

**Comment by cx1111** [comment]
These are done.

**Comment by cx1111** [comment]
I'll close this since people are adding their own issues for each desired feature.
