### ISSUE TITLE
How to extract AVG, Median and other from a wfdb signal?

### ISSUE THREAD

**Issue by PedroOlavo** [MIT-LCP/wfdb-python#242]
Hello everyone, i want to know how to get some details from a wfdb signal.
I'm interested in getting the average, the median, standard deviation,  variance, boxplot and histogram of fews signals. 
Thanks for the attention.

**Comment by Lucas-Mc** [comment]
Hey @PedroOlavo, thanks for the question! This package mainly just interfaces with the WFDB format and converts it to other forms such as numpy arrays, WAV, and MAT to name a few. I have compiled some example scripts you may want to use here!

**General Plotting**
```
# Import an ECG signal from the Apnea ECG database
>>> r = wfdb.rdrecord('a01', pn_dir='apnea-ecg')
# Truncate the signal to make it easier to see without zooming in
>>> r.p_signal = r.p_signal[:1000]
# Plot it as a general signal
>>> wfdb.plot_wfdb(record=r)
```
![WFDB_plot_ECG](https://user-images.githubusercontent.com/39505798/86499340-c0583780-bd58-11ea-8e56-7bb8bf5ed815.png)

**Average, Median, Standard Deviation, and Variance**
```
>>> import numpy as np
>>> np.average(r.p_signal)
-8.000000000000052e-05
>>> np.median(r.p_signal)
-0.04
>>> np.std(r.p_signal)
0.25513328595069673
>>> np.var(r.p_signal)
0.0650929936
```

**Boxplot**
```
>>> import matplotlib.pyplot as plt
>>> fig, ax = plt.subplots()
>>> ax.boxplot(r.p_signal)
{'whiskers': [<matplotlib.lines.Line2D object at 0x1219159b0>, <matplotlib.lines.Line2D object at 0x12190dd30>], 
 'caps': [<matplotlib.lines.Line2D object at 0x12190df28>, <matplotlib.lines.Line2D object at 0x12190d5f8>], 
 'boxes': [<matplotlib.lines.Line2D object at 0x1219150f0>],
 'medians': [<matplotlib.lines.Line2D object at 0x12190d710>], 
 'fliers': [<matplotlib.lines.Line2D object at 0x12192c320>], 
 'means': []}
>>> plt.show()
```
![MPL_boxplot](https://user-images.githubusercontent.com/39505798/86499512-a5d28e00-bd59-11ea-962d-df9ad170b509.png)

**Histogram**
```
>>> fig, ax = plt.subplots()
>>> ax.hist(r.p_signal)
(array([ 21.,  11., 365., 492.,  86.,   3.,   1.,   9.,   3.,   9.]),
 array([-0.825 , -0.5705, -0.316 , -0.0615,  0.193 ,  0.4475,  0.702 , 0.9565,  1.211 ,  1.4655,  1.72  ]), 
 <a list of 10 Patch objects>)
>>> plt.show()
```
![MPL_hist](https://user-images.githubusercontent.com/39505798/86499576-095cbb80-bd5a-11ea-94fa-1327e699b782.png)

I hope this helps and feel free to let me know if you have any further questions!

**Comment by PedroOlavo** [comment]
> Hey @PedroOlavo, thanks for the question! This package mainly just interfaces with the WFDB format and converts it to other forms such as numpy arrays, WAV, and MAT to name a few. I have compiled some example scripts (using the [Apnea ECG database](https://physionet.org/content/apnea-ecg/1.0.0/)) you may want to use here!
> 
> **General Plotting**
> 
> ```
> # Import an ECG signal from the Apnea ECG database
> >>> r = wfdb.rdrecord('a01', pn_dir='apnea-ecg')
> # Truncate the signal to make it easier to see without zooming in
> >>> r.p_signal = r.p_signal[:1000]
> # Plot it as a general signal
> >>> wfdb.plot_wfdb(record=r)
> ```
> 
> ![WFDB_plot_ECG](https://user-images.githubusercontent.com/39505798/86499340-c0583780-bd58-11ea-8e56-7bb8bf5ed815.png)
> 
> **Average, Median, Standard Deviation, and Variance**
> 
> ```
> >>> import numpy as np
> >>> np.average(r.p_signal)
> -8.000000000000052e-05
> >>> np.median(r.p_signal)
> -0.04
> >>> np.std(r.p_signal)
> 0.25513328595069673
> >>> np.var(r.p_signal)
> 0.0650929936
> ```
> 
> **Boxplot**
> 
> ```
> >>> import matplotlib.pyplot as plt
> >>> fig, ax = plt.subplots()
> >>> ax.boxplot(r.p_signal)
> {'whiskers': [<matplotlib.lines.Line2D object at 0x1219159b0>, <matplotlib.lines.Line2D object at 0x12190dd30>], 
>  'caps': [<matplotlib.lines.Line2D object at 0x12190df28>, <matplotlib.lines.Line2D object at 0x12190d5f8>], 
>  'boxes': [<matplotlib.lines.Line2D object at 0x1219150f0>],
>  'medians': [<matplotlib.lines.Line2D object at 0x12190d710>], 
>  'fliers': [<matplotlib.lines.Line2D object at 0x12192c320>], 
>  'means': []}
> >>> plt.show()
> ```
> 
> ![MPL_boxplot](https://user-images.githubusercontent.com/39505798/86499512-a5d28e00-bd59-11ea-962d-df9ad170b509.png)
> 
> **Histogram**
> 
> ```
> >>> import matplotlib.pyplot as plt
> >>> fig, ax = plt.subplots()
> >>> ax.hist(r.p_signal)
> (array([ 21.,  11., 365., 492.,  86.,   3.,   1.,   9.,   3.,   9.]),
>  array([-0.825 , -0.5705, -0.316 , -0.0615,  0.193 ,  0.4475,  0.702 , 0.9565,  1.211 ,  1.4655,  1.72  ]), 
>  <a list of 10 Patch objects>)
> >>> plt.show()
> ```
> 
> ![MPL_hist](https://user-images.githubusercontent.com/39505798/86499576-095cbb80-bd5a-11ea-94fa-1327e699b782.png)
> 
> I hope this helps and feel free to let me know if you have any further questions!

**Comment by PedroOlavo** [comment]
> Hey @PedroOlavo, thanks for the question! This package mainly just interfaces with the WFDB format and converts it to other forms such as numpy arrays, WAV, and MAT to name a few. I have compiled some example scripts (using the [Apnea ECG database](https://physionet.org/content/apnea-ecg/1.0.0/)) you may want to use here!
> 
> **General Plotting**
> 
> ```
> # Import an ECG signal from the Apnea ECG database
> >>> r = wfdb.rdrecord('a01', pn_dir='apnea-ecg')
> # Truncate the signal to make it easier to see without zooming in
> >>> r.p_signal = r.p_signal[:1000]
> # Plot it as a general signal
> >>> wfdb.plot_wfdb(record=r)
> ```
> 
> ![WFDB_plot_ECG](https://user-images.githubusercontent.com/39505798/86499340-c0583780-bd58-11ea-8e56-7bb8bf5ed815.png)
> 
> **Average, Median, Standard Deviation, and Variance**
> 
> ```
> >>> import numpy as np
> >>> np.average(r.p_signal)
> -8.000000000000052e-05
> >>> np.median(r.p_signal)
> -0.04
> >>> np.std(r.p_signal)
> 0.25513328595069673
> >>> np.var(r.p_signal)
> 0.0650929936
> ```
> 
> **Boxplot**
> 
> ```
> >>> import matplotlib.pyplot as plt
> >>> fig, ax = plt.subplots()
> >>> ax.boxplot(r.p_signal)
> {'whiskers': [<matplotlib.lines.Line2D object at 0x1219159b0>, <matplotlib.lines.Line2D object at 0x12190dd30>], 
>  'caps': [<matplotlib.lines.Line2D object at 0x12190df28>, <matplotlib.lines.Line2D object at 0x12190d5f8>], 
>  'boxes': [<matplotlib.lines.Line2D object at 0x1219150f0>],
>  'medians': [<matplotlib.lines.Line2D object at 0x12190d710>], 
>  'fliers': [<matplotlib.lines.Line2D object at 0x12192c320>], 
>  'means': []}
> >>> plt.show()
> ```
> 
> ![MPL_boxplot](https://user-images.githubusercontent.com/39505798/86499512-a5d28e00-bd59-11ea-962d-df9ad170b509.png)
> 
> **Histogram**
> 
> ```
> >>> import matplotlib.pyplot as plt
> >>> fig, ax = plt.subplots()
> >>> ax.hist(r.p_signal)
> (array([ 21.,  11., 365., 492.,  86.,   3.,   1.,   9.,   3.,   9.]),
>  array([-0.825 , -0.5705, -0.316 , -0.0615,  0.193 ,  0.4475,  0.702 , 0.9565,  1.211 ,  1.4655,  1.72  ]), 
>  <a list of 10 Patch objects>)
> >>> plt.show()
> ```
> 
> ![MPL_hist](https://user-images.githubusercontent.com/39505798/86499576-095cbb80-bd5a-11ea-94fa-1327e699b782.png)
> 
> I hope this helps and feel free to let me know if you have any further questions!

**Comment by PedroOlavo** [comment]
Hi @Lucas-Mc, how are you? Thanks for the ansewr, but i realized that when i read the signal with wfdb it's become a numpy matrix. So i turned it into a DataFrame and get all the stuff i needed including the plot of signal using a line chart.
