### ISSUE TITLE
Negative Subtype Values Error

### ISSUE THREAD

**Issue by derek-nakano** [MIT-LCP/wfdb-python#248]
I'm having trouble writing out annotation files with negative subtype values.  This was previously mentioned in issue #89 and was supposedly resolved, but the problem still exists for me.  Looking at annotation.py, we can see that the check for negative values is still there.
![image](https://user-images.githubusercontent.com/59340088/90197786-99901680-dd84-11ea-911a-1f1c9e8459cf.png)

Am I looking at an outdated file?  If so, can you link me the updated version that resolves this issue?  Thank you!

**Comment by Lucas-Mc** [comment]
I am not sure this was ever fixed actually... the git blame for that chunk of code is September 25th, 2017 while the issue was raised in December?
