### ISSUE TITLE
Problems Accessing MIMIC-III Waveform Database

### ISSUE THREAD

**Issue by fabbra** [MIT-LCP/wfdb-python#254]
I would like to access the records from the [MIMIC-III Waveform Database](https://physionet.org/content/mimic3wdb/1.0/) remotely via wfdb-python. Since the entire database is quite large I first would like to access the headers remotely and only select a subset of records to download based on the availability of some waveforms and other characteristics from the header files.

Here's what I've tried:
```
import wfdb
recs = wfdb.get_record_list('mimic3wdb')
r = wfdb.rdrecord(recs[0], pn_dir='mimic3wdb')
```
The above example fails saying _HTTPError: 404 Client Error: Not Found for url: https://physionet.org/files/mimic3wdb/1.0/.hea_

Adapting it as follows gives me at least an URL which seems closer to the final goal:
```
import wfdb
recs = wfdb.get_record_list('mimic3wdb')
wfdb.io.download.set_db_index_url('https://physionet.org/content/')
r = wfdb.io.rdrecord(recs[0], pn_dir='mimic3wdb')
```
But still it fails saying _HTTPError: 404 Client Error: Not Found for url: https://physionet.org/content/mimic3wdb/1.0/.hea_

Is this an known error?
If not, could someone provide me with a minimum working example on how to access all headers (and eventually download signals) of the MIMIC-III Waveform Database in an iterative manner (without downloading the entire database to disk first!).

**Comment by Lucas-Mc** [comment]
Hey @fabbra, I have to look into this further but you can use this for now:
```
record = wfdb.rdrecord(recs[0].split('/')[1], pn_dir='mimic3wdb/'+recs[0])
```
or for numerics:
```
record = wfdb.rdrecord(recs[0].split('/')[1]+'n', pn_dir='mimic3wdb/'+recs[0])
```

This may not work for all the records in `recs` since some only have a numerics file but this should be a good start. You could do this:
```
import wfdb
recs = wfdb.get_record_list('mimic3wdb')
for r in recs:
    try:
        record = wfdb.rdrecord(r.split('/')[1], pn_dir='mimic3wdb/'+r)
    except:
        pass
    try:
        record_n = wfdb.rdrecord(r.split('/')[1]+'n', pn_dir='mimic3wdb/'+r)
    except:
        pass
```
This is ugly, so I'll work on finding a better solution.

**Comment by fabbra** [comment]
Hey @Lucas-Mc, thanks for your prompt reply!
Unfortunately neither of your two suggestions work for me since I always get the following error in `wfdb\io\record.py`:
```
   1248     contents = [line.decode('utf-8').strip() for line in response.content.splitlines()]
   1249     version_number = [v for v in contents if 'Version:' in v]
-> 1250     version_number = version_number[0].split(':')[-1].strip().split('<')[0]
   1251
   1252     return version_number

IndexError: list index out of range
```
Looking forward for a better solution. Thanks a lot in advance.

**Comment by Lucas-Mc** [comment]
@fabbra Strange, both work for me on the latest version. I got that error when I misspelled `mimic3wdb` though. What version are you on?

**Comment by fabbra** [comment]
So far I was using wfdb version `3.1.0` which I obtained via `pip install wfdb`. 
I have now switched to the latest git using `pip install git+https://github.com/MIT-LCP/wfdb-python.git` (now `pip list` tells me that I am using version `3.1.1`). However this did not solve my problem.

Executing the following lines results in the same `IndexError` mentioned above:
```
import wfdb
recs = wfdb.get_record_list('mimic3wdb')
record = wfdb.rdrecord(recs[0].split('/')[1], pn_dir='mimic3wdb/'+recs[0])
```

**Comment by gloryren** [comment]
when i run this:
`# Demo 17 - Download all the WFDB records and annotations from a small PhysioNet Database

# Make a temporary download directory in your current working directory
cwd = os.getcwd()
dl_dir = os.path.join(cwd, 'tmp_dl_dir')

# Download all the WFDB content
wfdb.dl_database('mitdb', dl_dir=dl_dir)`

got
`ValueError: The database https://physionet.org/files/mitdb/1.0.0/1.0.0 has no WFDB files to download`

using wfdb3.1.0: 404 error, there is a %5C problem
update to 3.1.1 , got ValueError above.

**Comment by Lucas-Mc** [comment]
Sounds like a Windows thing, I really need to get my Windows computer set up so I can test on both OSs!! Anyway, I'll try and find it ... Do you have a stack trace? What is `recs[0]`?

**Comment by fabbra** [comment]
> Sounds like a Windows thing,

I confirm! When running the same commands in the Unix subsystem (Ubuntu) on my Win64 machine this works without errors.

> Do you have a stack trace? 
```
In [1]: import wfdb

In [2]: recs = wfdb.get_record_list('mimic3wdb')

In [3]: record = wfdb.rdrecord(recs[0].split('/')[1], pn_dir='mimic3wdb/'+recs[0])
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-3-1b0d25728761> in <module>
----> 1 record = wfdb.rdrecord(recs[0].split('/')[1], pn_dir='mimic3wdb/'+recs[0])

~\venv\Lib\site-packages\wfdb\io\record.py in rdrecord(record_name, sampfrom, sampto, channels, physical, pn_dir, m2s, smooth_frames, ignore_skew, return_res, force_channels, channel_names, warn_empty)
   2740     if (pn_dir is not None) and ('.' not in pn_dir):
   2741         dir_list = pn_dir.split(os.sep)
-> 2742         pn_dir = posixpath.join(dir_list[0], get_version(dir_list[0]), *dir_list[1:])
   2743
   2744     if record_name.endswith('.edf'):

~\venv\Lib\site-packages\wfdb\io\record.py in get_version(pn_dir)
   1248     contents = [line.decode('utf-8').strip() for line in response.content.splitlines()]
   1249     version_number = [v for v in contents if 'Version:' in v]
-> 1250     version_number = version_number[0].split(':')[-1].strip().split('<')[0]
   1251
   1252     return version_number

IndexError: list index out of range
```

> What is `recs[0]`?
```
In [4]: recs[0]
Out[4]: '30/3000003/'
```

Hope that helps to further debug the thing...

**Comment by Lucas-Mc** [comment]
Hey @fabbra, I just got my Windows machine to reproduce the error... let the debugging begin!

**Comment by Lucas-Mc** [comment]
Hey @fabbra, the issue was very subtle and not picked up on the stack trace with this line:

https://github.com/MIT-LCP/wfdb-python/blob/4d4c3542ba7425294e635e429e98a88d37a76ba8/wfdb/io/record.py#L2741

Silly me using `os.sep` for a URL instead of file path.. update coming soon!

**Comment by fabbra** [comment]
@Lucas-Mc, thanks that works for `rdrecord()`, however, aren't there are other occurences of `dir_list = pn_dir.split(os.sep)` which need to be fixed, e.g. in `rdheader()`?
https://github.com/MIT-LCP/wfdb-python/blob/4d4c3542ba7425294e635e429e98a88d37a76ba8/wfdb/io/record.py#L2571
It's not the only occurence but just one example...

**Comment by Lucas-Mc** [comment]
Hey @fabbra, yes I have to look around at other instances and will fix them in a separate pull request if they occur. Thanks for reminding me!

**Comment by fabbra** [comment]
> 
> 
> @Lucas-Mc, thanks that works for `rdrecord()`, however, aren't there are other occurences of `dir_list = pn_dir.split(os.sep)` which need to be fixed, e.g. in `rdheader()`?
> 
> https://github.com/MIT-LCP/wfdb-python/blob/4d4c3542ba7425294e635e429e98a88d37a76ba8/wfdb/io/record.py#L2571
> 
> It's not the only occurence but just one example...

just found another occurence which might need a fix: 
https://github.com/MIT-LCP/wfdb-python/blob/09ca340e41fdbf8f13334778259d447e8b191841/wfdb/io/download.py#L281

**Comment by fabbra** [comment]
Similar question on the same subject, is there a way to iterate through all records of the [MIMIC-III Waveform Database **Matched Subset**](https://physionet.org/content/mimic3wdb-matched)?

The method suggested by you above does not work since the filename of the header has a postfix, i.e. it does not correspond exactly to the name in the RECORDS file, e.g. for `p000020` the header file is not called `p000020.hea` but `p000020-2183-04-28-17-47.hea`

A potential way might be to read a different records file, e.g. `RECORDS-waveforms` but that doesn't work using `wfdb.get_record_list()', does it?

**Comment by Div12345** [comment]
Hi,
Can this issue be kept open till it is totally resolved? I just came across the error again while using wfdb.rdann(). I think if I understand this right, I see atleast 8 direct instances just by doing a search of pn_dir.split and only one of them has been changed in the master right now.
