### ISSUE TITLE
MGH/MF Waveform Database annotation not loading

### ISSUE THREAD

**Issue by smolendawid** [MIT-LCP/wfdb-python#255]
Reading annotations from MGH/MF Waveform Database (mghdb) results in the following error:

`annotation = wfdb.rdann(record_path, extension='ari')`

> KeyError: 'Passing list-likes to .loc or [] with any missing labels is no longer supported, see https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#deprecate-loc-reindex-listlike'

**Comment by smolendawid** [comment]
Obviously downgrading pandas helps

**Comment by Lucas-Mc** [comment]
Hey @smolendawid, thanks for posting your find! I fixed the bug for this case and it might show up in the future since there's other implementations of `.loc` but I'm going to wait to see if any bugs pop up since it acts fine right now.

**Comment by smolendawid** [comment]
Great, thank you!
