### ISSUE TITLE
wrann not working with only label_store set in Annotation

### ISSUE THREAD

**Issue by Lullatsch** [MIT-LCP/wfdb-python#260]
Hi I think the `wrann` method inside `wfdb.io.Annotation` might not be working as intended right now. 

When I try to write a new annotation with only the label_store field set, I get a Nonetype error inside `wfdb.io.Annotation.calc_core_bytes` (line 930) where it says `data_bytes.append(field2bytes('samptype', [sampdiff[i], self.symbol[i]]))`, because self.symbol is None (and thus unsubscriptable). 

From the documentation it should however also be possible to only use label_store as a field in my Annotation.

**Comment by Tomwhiting1987** [comment]
I'm also getting exactly the same error when I put in a label store array instead of a symbol array. I thought it was something silly I was doing! Is it possible to fix this? It does suggest in the documentation that this should work.
