### ISSUE TITLE
Downloads fail on Windows

### ISSUE THREAD

**Issue by lbugnon** [MIT-LCP/wfdb-python#262]
Hi, URL generation is failing in windows when using dl_database, For example 

```
wfdb.dl_database('ltdb', os.path.join("data", "ltdb"))
ValueError: The database https://physionet.org/files/mitdb/1.0.0/1.0.0 has no WFDB files to download

```
here "/1.0.0" is repeated

**Comment by gloryren** [comment]
same，not solved

**Comment by jlnbotello** [comment]
Quick workaround... (could break other db downloads)
Inside "...wfdb\io"  edit file "download.py" line 282.
Original
```
        db_url = posixpath.join(config.db_index_url, db_dir, record.get_version(db_dir))
```
Modified
```
        db_url = posixpath.join(config.db_index_url, db_dir''', record.get_version(db_dir)''')
```

**Comment by lbugnon** [comment]
The issue is that the os.sep should be replaced with a "/" in the if cited by @jlnbotello, as the url uses / and not \

**Comment by jlnbotello** [comment]
As you mention, there is a version string repeated("/1.0.0") . You are you right with reparators. But why changing the separator solved the repetition?

**Comment by jlnbotello** [comment]
You are right @lbugnon !!!

```
    if '/' not in db_dir:
        db_url = posixpath.join(config.db_index_url, db_dir , record.get_version(db_dir))
    else:
        db_url = posixpath.join(config.db_index_url, db_dir)
````

**Comment by Lucas-Mc** [comment]
Thanks for the catch @lbugnon! Silly mistake during development which didn't show up on my Mac 🤦 This reminds me and further increases my desire to add Windows OS testing to Travis.. hopefully to be implemented soon!
