### ISSUE TITLE
making sense of data format

### ISSUE THREAD

**Issue by tryinglibrary** [MIT-LCP/wfdb-python#30]
Hi,

I just downloaded some acceleration data from the physionet database but the values I get are huge (e.g. 1.07841715e+198). Reading the FAQ I guess the signal format is "format 16" (using two's complement) but I'm still confused. I would expect values ranging from -20 to +20 m/s^2. Can you please help?

Below are the first 4 lines of:
https://physionet.org/physiobank/database/ltmm/LabWalks/co001_base.hea

co001_base 6 100 3801
co001_base.dat 16 47916.5958(-53949)/g 0 0 -10008 -15948 0 v-acceleration
co001_base.dat 16 70148.6031(4980)/g 0 0 -6474 -18391 0 ml-acceleration
co001_base.dat 16 54691.0073(34671)/g 0 0 15947 -23295 0 ap-acceleration

Thanks a lot,
David

**Comment by cx1111** [comment]
Hello

How exactly did you get these values? I just tried reading the signal with both the wfdb-python rdsamp and the original C version of rdsamp:

```
[sig, fields]=wfdb.rdsamp('ltmm/LabWalks/co001_base', pbdl=1)

>>> sig
```
array([[  9.17030921e-01,  -1.63281940e-01,  -3.42359758e-01,
          1.65484292e+01,  -2.94991384e+00,   6.40017927e+00],


`rdsamp -r ltmm/LabWalks/co001_base -P | more`
          0.000	     0.91703092	    -0.16328194	    -0.34235976	    16.54842925	    -2.94991384	     6.40017927
          0.010	     0.92560833	    -0.15475718	    -0.35106320	    18.98879305	    -4.23962180	     6.20966406
          0.020	     0.92846746	    -0.15192035	    -0.35397044	    21.43836577	    -5.55277899	     5.68716195

**Comment by tryinglibrary** [comment]
Thank you so much Chen,

I guess the problem was the way I was reading the data. Problem fixed. Thanks a lot.
