### ISSUE TITLE
reading RR as txt from nsrdb

### ISSUE THREAD

**Issue by bdekoven** [MIT-LCP/wfdb-python#303]
Hello -

can you please suggest the Python command for ann2r which will provide RR intervals as text?
This would be for database nsrdb.

Thank you,
Benjamin DeKoven

**Comment by Lucas-Mc** [comment]
Hey @bdekoven, `ann2rr` has a parameter `as_array` which, by default, is set to `True`. This means the function will return a numpy array. After you have the numpy array, you can convert that to text with `numpy.savetxt`. Hope this helps!

**Comment by bdekoven** [comment]
Thank you very much.

Ben DeKoven
