### ISSUE TITLE
Module structure

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/wfdb-python#31]
How about the following:

- headers.py: Functions and definitions for reading and writing WFDB header files. No dependencies. 
  - rdheader
  - wrheader
  - The header fields dictionary/list
  - Other private helpers
- signals.py: Functions and definitions for reading and writing WFDB record (signal+header) files. Uses headers.py.
  - rdsamp
  - wrsamp
  - Other private helpers (namely rddat and wrdat)
- annotations.py: Functions and definitions for reading and writing WFDB annotation files. Uses headers.py.
  - rdann
  - wrann
  - Other private helpers.

**Comment by alistairewj** [comment]
Seems like a sensible structure.

**Comment by tompollard** [comment]
Sounds clear to me too.
