### ISSUE TITLE
ValueErrors for some ids from mghdb Dataset 

### ISSUE THREAD

**Issue by MaxBenChrist** [MIT-LCP/wfdb-python#33]
Thanks for providing the wfdb python package.

I downloaded the [mghdb dataset](https://physionet.org/physiobank/database/mghdb/) locally.

When extracting the time series for this data set I get errors for some ids. 

``` Python
sig, fields = wfdb.rdsamp('/mghdb/mgh026')
ValueError: could not broadcast input array from shape (6912000) into shape (7128000)
```

``` Python
sig, fields = wfdb.rdsamp('/mghdb/mgh175')
ValueError: could not broadcast input array from shape (5031488) into shape (5555520)
```

``` Python
sig, fields = wfdb.rdsamp('/mghdb/mgh196')
ValueError: could not broadcast input array from shape (6739200) into shape (6946560)
```

``` Python
sig, fields = wfdb.rdsamp('/mghdb/mgh199')
ValueError: could not broadcast input array from shape (6739200) into shape (6998400)
```

``` Python
sig, fields = wfdb.rdsamp('/mghdb/mgh210')
ValueError: operands could not be broadcast together with shapes (7144790,) (7144789,)
```

The other ids can be loaded without a problem

**Comment by cx1111** [comment]
Thanks very much for pointing this out. I had a look at the first file and it appears the dat file has fewer samples than the header states. I'll probably end up changing the header files to reflect the true samples or see if the data files got changed somehow.

**Comment by MaxBenChrist** [comment]
Okay, Glad to help. Let me know when I can support you

**Comment by cx1111** [comment]
I'll make the changes to the data files after confirming with my coworker who will be in later  today. The sorted changes should be reflected on the website tomorrow. I'll post here to let you know. Cheers.

**Comment by MaxBenChrist** [comment]
Awesome 👍

**Comment by cx1111** [comment]
Should be fixed. Changes will show up tomorrow. Thanks.

**Comment by MaxBenChrist** [comment]
Awesome, thanks for fixing this so fast 👏
