### ISSUE TITLE
own data

### ISSUE THREAD

**Issue by hongjianyuan** [MIT-LCP/wfdb-python#349]
![image](https://user-images.githubusercontent.com/41334719/159294998-ee633029-e025-4e77-8f52-a564ddcd0d9a.png)
I use my own data, 250hz ECG signal, a total of 2000 points, but the result of XQRS is very bad, how can I solve it

**Comment by wenh06** [comment]
Use a deep learning model instead, which largely outperforms the traditional methods, see [here](https://github.com/DeepPSP/torch_ecg/tree/master/benchmarks/train_multi_cpsc2019) for example.
