### ISSUE TITLE
error when processing record

### ISSUE THREAD

**Issue by cmpotes** [MIT-LCP/wfdb-python#35]
Hi, 

I am trying to run wfdb with the following record \matched\\s00001\\s00001-2896-10-10-00-31'

as 
tstart = 14428365
tend = 14428375
sig, fields = wfdb.rdsamp(filename,sampfrom=tstart,sampto=tend)

and I am getting the following error
*** TypeError: exit expected at most 1 arguments, got 2

It runs if I do 
sig, fields = wfdb.rdsamp(filename,sampfrom=14428365) or
sig, fields = wfdb.rdsamp(filename)

**Comment by cx1111** [comment]
Thanks for finding this. I've fixed it and added a few unit tests to keep track of it. If there are still issues reading multi-segment signals let me know!
