### ISSUE TITLE
check the headrs in .hea files.

### ISSUE THREAD

**Issue by Mehrab-Shahbazi** [MIT-LCP/wfdb-python#360]
Hi, I want to read some files from physionet that are records of some patients.
there are files in .hea format that represent which signals are recorded.
I need to check which signal has been recorded in those files in python.
I'll be thankful if you help me.

**Comment by briangow** [comment]
@Mehrab-Shahbazi , if you use the [`rdrecord`](https://wfdb.readthedocs.io/en/latest/wfdb.html) function, it will return the signal names along with other useful information (sampling frequency, etc). 

```
record = wfdb.rdrecord(<file_path>)
sigs = record.sig_name
```
