### ISSUE TITLE
Type annotations

### ISSUE THREAD

**Issue by bemoody** [MIT-LCP/wfdb-python#378]
It would be helpful to have Python type annotations as a way to catch bugs (in wfdb itself and in applications) and as a way to more rigorously document the API.

A couple of issues would need to be resolved:

1. Decide on a style for writing annotations.

You could `import typing` and then write `def foo(x: typing.Sequence[int]) -> typing.Union[None, typing.List]`, but that's very noisy.

You could instead write `from typing import (List, Sequence, Union)` and then write `def foo(x: Sequence[int]) -> Union[None, List]`, which is a little less ugly, but requires maintaining a list of imports at the top of the file.

It's also, honestly, a bit confusing (hard to remember which names refer to concrete classes in the standard library, and which are abstract classes that are only useful for typing.  Quick, without looking it up, tell me the difference between `BinaryIO` and `BytesIO`.)

2. Find a way to actually type-check the package.

Annotations are useless if we can't check that they are correct or at least syntactically valid.

mypy will give an error if there are any binary modules in use that don't have a corresponding "stub" file.  If there's a way to suppress this error, I haven't found it.  That makes it very difficult to do any automated checking.

Of the modules used by wfdb, `requests`, `pandas`, `matplotlib`, and `scipy` are currently lacking these stubs.  (`numpy` has its own.)

It's possible to use third-party stub files, with all the caveats that implies.  mypy itself suggests using the third-party `types-requests` package for `requests`.  For `pandas` and `matplotlib` there is the third-party `data-science-types` package, which is apparently abandoned.  I don't know about `scipy`.

Fixing bugs in wfdb is one thing, but this issue seems to be largely out of our control.

**Comment by tompollard** [comment]
I wasn't familiar with stub files until now. Just been reading up on them at: https://peps.python.org/pep-0484/#stub-files

> You could instead write from typing import (List, Sequence, Union) and then write def foo(x: Sequence[int]) -> Union[None, List], which is a little less ugly, but requires maintaining a list of imports at the top of the file.

My preference is this approach. I don't think it's too bigger deal to have a list of type imports at the top of the file, and it's definitely cleaner than the alternative (`def foo(x: typing.Sequence[int])` etc.)

> Annotations are useless if we can't check that they are correct or at least syntactically valid.

I don't see a good reason not to use them for basic/built-in data types. At the very least it forces people to think about typing when they're writing a function.

**Comment by bemoody** [comment]
> I don't see a good reason not to use them for basic/built-in data types. At the very least it forces people to think about typing when they're writing a function.

The docstring convention does that already.  But the docstrings aren't checked automatically, and the consequence is that many of them are *wrong*.

The best thing would be to have type annotations that are both machine-readable and checked automatically, so they don't require additional manual effort to maintain.

The next best thing, perhaps, would be to *remove* type annotations from the docstrings and replace them with machine-readable annotations, assuming the annotations are shown in the online documentation and are understandable to users.

**Comment by tompollard** [comment]
> The docstring convention does that already. But the docstrings aren't checked automatically, and the consequence is that many of them are wrong.

It might be easier to chat about this in person, but my understanding is that there some form of checking that goes on for type annotations. If we include type annotations and pass an unsupported type as an argument, doesn't the function raise an error?

**Comment by bemoody** [comment]
That's what I'm saying, Python doesn't do that.  You need another program to do that.  mypy is one, which I think is the most popular, but there may be others.

**Comment by cx1111** [comment]
Linters like `pylint` should check, but we have way too many errors to actually run it on our code :P

The primary reason I want this is to make it easier to follow along while adding/modifying code in the editor, which highlights local types and errors, even if the rest of the file contains a giant sack of type related errors. This provides a lot of value and helps make the package more maintainable just by itself.

**Comment by tompollard** [comment]
I'm not clear what I'm seeing in the screenshot, but I get the general idea. I think your argument is a good one and I am supportive of type hints.

@cx1111 I was going to say that the person who needs convincing is @bemoody, but then I scrolled to the top of the issue to see that @bemoody the initial suggestion comes from him!

I think the style question is resolved (e.g. `from typing import (List, Sequence, Union)` is preferred) so the remaining question is how best to type check in the github CI workflow?

**Comment by cx1111** [comment]
> I'm not clear what I'm seeing in the screenshot, but I get the general idea. I think your argument is a good one and I am supportive of type hints.

I'm hovering over `url` on line 787. The editor shows it as a `str` due to the earlier type hint.

> I think the style question is resolved (e.g. `from typing import (List, Sequence, Union)` is preferred) so the remaining question is how best to type check in the github CI workflow?

We don't, for now. We have too many lint errors. If we started with a clean slate, we could run pylint in the CI. Adding the type hints will better allow us to whittle down the errors eventually.
