### ISSUE TITLE
Downloads fail on Windows

### ISSUE THREAD

**Issue by kbrose** [MIT-LCP/wfdb-python#40]
Main problem is prevalence of using `os.path.join()` to create URLs, on Windows this will use backslashes to join the arguments instead of forward slash, ending up with errors like

```
>>> import wfdb; import os; wfdb.dldatabasefiles('ltstdb', os.getcwd(), ['s20011.hea', 's20011.dat'], overwrite=True)
Downloading files...
multiprocessing.pool.RemoteTraceback:
... < SNIP > ...
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://physionet.org/physiobank/database/ltstdb%5Cs20011.hea
```

(of course `%5C` is a backslash).

Probably want to use `posixpath` instead?

**Comment by gloryren** [comment]
> Main problem is prevalence of using `os.path.join()` to create URLs, on Windows this will use backslashes to join the arguments instead of forward slash, ending up with errors like
> 
> ```
> >>> import wfdb; import os; wfdb.dldatabasefiles('ltstdb', os.getcwd(), ['s20011.hea', 's20011.dat'], overwrite=True)
> Downloading files...
> multiprocessing.pool.RemoteTraceback:
> ... < SNIP > ...
> requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http://physionet.org/physiobank/database/ltstdb%5Cs20011.hea
> ```
> 
> (of course `%5C` is a backslash).
> 
> Probably want to use `posixpath` instead?

have solved this?
i have this problem now, and i check WFDB have use posixpath now ,but why still this happened?
