### ISSUE TITLE
Use of sys.exit instead of raising errors

### ISSUE THREAD

**Issue by kbrose** [MIT-LCP/wfdb-python#41]
Using sys.exit when things go wrong boots me out of my Python shell. I think the more pythonic way to handle problems is to raise an error, e.g.

```python
# Instead of using
# sys.exit('The database contains no annotators with extension: ', a)
# I suggest using
raise ValueError('The database contains no annotators with extension: ', a)
```

Does that sound reasonable to others?

**Comment by cx1111** [comment]
Changed. Thanks.
