### ISSUE TITLE
Suggestion to update resample_ann in legacy code

### ISSUE THREAD

**Issue by langestefan** [MIT-LCP/wfdb-python#414]
Hi,

I have some legacy code that uses `resample_ann` with the old format `def resample_ann(resampled_t, ann_sample)` from and before version 3.3.0. I am looking to update this to the new format `resample_ann(ann_sample, fs, fs_target)` so I can use the latest version however I am not sure what would be the best way to do this, since this is my first time using wfdb. 

Thank you very much for any suggestions.

**Comment by briangow** [comment]
[Version 4.0](https://pypi.org/project/wfdb/) of wfdb has been released to PyPI. Therefore, you should be able to upgrade your `wfdb` package (after activating your local environment). From the directory with your environment (named `env` in this example) you can:

```
source env/bin/activate
pip install wfdb --upgrade
```

**Comment by langestefan** [comment]
> [Version 4.0](https://pypi.org/project/wfdb/) of wfdb has been released to PyPI. Therefore, you should be able to upgrade your `wfdb` package (after activating your local environment). From the directory with your environment (named `env` in this example) you can:
> 
> ```
> source env/bin/activate
> pip install wfdb --upgrade
> ```

Hi, thanks, I managed this. Maybe my question wasn't clear, I mean how can I replace the actual function calls to `resample_ann` with the new method in the best way? The interface has changed to accept sampling rates so I wonder have you changed your examples accordingly or something else so I can take a look at.

**Comment by briangow** [comment]
@langestefan , I'm not sure exactly what you were doing in your old code but this is the info for the new variables:

```
    ann_sample : ndarray
        Array of annotation locations.
    fs : int
        The starting sampling frequency.
    fs_target : int
        The desired sampling frequency.
```

I believe `ann_sample` should be the same as before. You can get `fs` from the record:

```
record = wfdb.rdrecord('100', pn_dir='mitdb')
record.fs
```

`fs_target` is the desired sampling frequency.

**Comment by langestefan** [comment]
@briangow thanks, I got it working :) I will close this now
