### ISSUE TITLE
`SoundFile` is not pip installable on M1 mac

### ISSUE THREAD

**Issue by briangow** [MIT-LCP/wfdb-python#421]
`SoundFile==0.10.3` is not pip installable on an arm64/M1 mac. To get around this issue you need to download an arm64 .whl from: https://github.com/bastibe/python-soundfile/releases and install it with `pip install /path/to/file.whl`.

**Comment by bemoody** [comment]
0.11.0 is released so this should be fixed now.  If there's anything that doesn't work with 0.11.0, please reopen or open a new issue.
