### ISSUE TITLE
Time taken for reading large wfdb files

### ISSUE THREAD

**Issue by vinay-hebb** [MIT-LCP/wfdb-python#423]
Suppose, there is a large wfdb file of 100 hours. If I read wfdb file using rdrecord with sampfrom and sampto corresponding to 98 and 99 hours, will the api read 0-98 hours and ignores this data or will it directly jumps to data between 98-99 hours. In other words, does reading execution speed vary in these two cases?

**Comment by vinay-hebb** [comment]
I just found [this](https://stackoverflow.com/a/69714434/11471226). Python also should use libraries similar to C internally. So, specifying sampto and sampfrom should reduce the time significantly. Let me know if my conclusion is incorrect otherwise I will close this issue

**Comment by bemoody** [comment]
You're correct - the package will skip over the first 98 hours and only read the one hour of data that you requested.

At least, that's how it's designed to work - if you find it works differently, please let us know so we can try to fix it. :)
