### ISSUE TITLE
.ecg format File reading error

### ISSUE THREAD

**Issue by 1358467720** [MIT-LCP/wfdb-python#425]
there is my code:

```python
from ishneholterlib import Holter

#Load a file from disk:
x = Holter("./data/chf202.ecg")
x.load_data()
```

there is error:
```
C:\Users\songHat\miniconda3\envs\hospital\python.exe D:\all_codes\hospital\mse\mse.py 
Traceback (most recent call last):
  File "D:\all_codes\hospital\mse\mse.py", line 10, in <module>
    x = Holter('./data/chf202.ecg')
  File "C:\Users\songHat\miniconda3\envs\hospital\lib\site-packages\ishneholterlib\__init__.py", line 65, in __init__
    self.load_header()
  File "C:\Users\songHat\miniconda3\envs\hospital\lib\site-packages\ishneholterlib\__init__.py", line 123, in load_header
    self.var_block = get_val(filename, 522, 'a'+str(self.var_block_size)).split(b'\x00')[0]
  File "C:\Users\songHat\miniconda3\envs\hospital\lib\site-packages\ishneholterlib\__init__.py", line 20, in get_val
    val = val[0]
IndexError: index 0 is out of bounds for axis 0 with size 0
```

**Comment by 1358467720** [comment]
can anyone help me? really appreciate !

**Comment by 1358467720** [comment]
there is data
[congestive-heart-failure-rr-interval-database-1.0.0.zip](https://github.com/MIT-LCP/wfdb-python/files/9640716/congestive-heart-failure-rr-interval-database-1.0.0.zip)

**Comment by briangow** [comment]
@1358467720 , have you attempted to use the [WFDB](https://wfdb.io/) toolbox? In the Python version of the toolbox you can read this annotation file directly from the PhysioNet servers with:

```
import wfdb
ann = wfdb.rdann('chf202', 'ecg', pn_dir='chf2db')
```

**Comment by 1358467720** [comment]
@briangow really thank your help! but in this data, I want to read the data with code:

```python
import wfdb

record = wfdb.rdrecord('chf202', pn_dir='chf2db')
print(record.record_name)
```
I get a error here:

```
Traceback (most recent call last):
  File "D:\all_codes\EEG\数据分析\mse\mse.py", line 9, in <module>
    record = wfdb.rdrecord('chf202', pn_dir='chf2db')
  File "C:\Users\songHat\miniconda3\envs\EEG\lib\site-packages\wfdb\io\record.py", line 2039, in rdrecord
    record.check_read_inputs(
  File "C:\Users\songHat\miniconda3\envs\EEG\lib\site-packages\wfdb\io\record.py", line 620, in check_read_inputs
    raise ValueError("sampto must be greater than sampfrom")
ValueError: sampto must be greater than sampfrom

Process finished with exit code 1
```
how to fix it? thank you!

**Comment by briangow** [comment]
@1358467720 my understanding from the project description for `chf2db` (https://physionet.org/content/chf2db/1.0.0/) is that the ECG waveform samples are not available - only the annotations are available. As mentioned in the project description you might want to take a look at this project if you need the waveforms + annotations: https://physionet.org/content/chfdb/1.0.0/ .

**Comment by briangow** [comment]
@1358467720 , yes, these appear to be two independent projects. If you need waveform signals + annotations you will have to use the https://physionet.org/content/chfdb/1.0.0/ project.

**Comment by 1358467720** [comment]
thank you again. But other data is not suitable for me
