### ISSUE TITLE
[Question] How could labels and ticks be removed?

### ISSUE THREAD

**Issue by 9kwon** [MIT-LCP/wfdb-python#438]
Thank you for developing the useful package first.
I am using wfdb-python for Physionet ECG data set to get just images.
The problem is I cannot remove any labels and ticks for clear plot images.
I was trying to change options based on matplotlib, pyplot but all failed.
How could I get just simple line images for ECG?

**Comment by bemoody** [comment]
If you call `wfdb.plot_wfdb` with `return_fig=True`, it gives you a `Figure` object which you can customize before calling `plt.show()`.

For example to remove all of the horizontal/vertical ticks and labels you could do:
```
import wfdb
import matplotlib.pyplot as plt

r = wfdb.rdrecord('100', pn_dir='mitdb/1.0.0', sampto=1000)

f = wfdb.plot_wfdb(r, return_fig=True)

for a in f.axes:
    a.set_xticks([])
    a.set_yticks([])
    a.set_xlabel(None)
    a.set_ylabel(None)

plt.show()
```

But if you really want to make the plot look a particular way, it may be easier to use matplotlib directly, not using `wfdb.plot_wfdb` at all.
