### ISSUE TITLE
error when running processing.ann2rr

### ISSUE THREAD

**Issue by BarAbba39** [MIT-LCP/wfdb-python#453]
228     out_interval = time_interval / (60 * 60)
    229 else:
--> 230     out_interval = np.around(time_interval * ann.fs).astype(**np.int)**
    232 if as_array:
    233     return out_interval

File ---/venv/lib/python3.10/site-packages/numpy/__init__.py:284, in __getattr__(attr)
    281     from .testing import Tester
    282     return Tester
--> 284 raise AttributeError("module {!r} has no attribute "
    285                      "{!r}".format(__name__, attr))

error: np has no attribute np.int

np.int was deprecated in 2021

**Comment by tompollard** [comment]
This issue should be fixed in Version 4.1.2, now available on PyPI. 

Please update your installation with:

```
pip install wfdb --upgrade
```
