### ISSUE TITLE
What is ann.chan and how to use it?

### ISSUE THREAD

**Issue by Dubrzr** [MIT-LCP/wfdb-python#47]
Hello,

I don't get what the ann.chan variable is:
```
t = 'nsrdb/18177'
sig, fields = wfdb.srdsamp(t)
fs = fields['fs']
ann = wfdb.rdann(t, 'atr')
print(fields)
>> {'fs': 128.0, 'signame': ['ECG1', 'ECG2'], 'units': ['mV', 'mV'], 'comments': ['26 F']}
print(numpy.unique(ann.chan))
>> [ 0  1  2 16 17 18 32 33 34]
```
Here we have 2 signals but it seems that there are 9 different channels; I thought that len(signal)==len(channels), are they different things? How do I associate an annotation channel with a signal?

I've also tested plotrec:
```
record = wfdb.rdsamp('nsrdb/18177', sampto = 1000)
ann = wfdb.rdann('nsrdb/18177', 'atr', sampto = 1000)
wfdb.plotrec(record, annotation=ann, title='Record nsrdb/17453', timeunits = 'seconds', annch=[0, 1])
```
Which gives:
![image](https://cloud.githubusercontent.com/assets/3718838/25617932/f49a8c46-2f44-11e7-9f33-70b66a0c6cb6.png)
Here I specified  annch=[0, 1] as I understood that ECG1=channel 0 and ECG2=channel 1.
But from what I understand, each annotation is associated with a specific channel: ann.chan[x] is associated with ann.anntype[x] and ann.annsamp[x], where ann.chan[x] specifies the signal channel on which there is an annotation. Shouldn't plotrec display annotations on the corresponding channel instead?

Or maybe I missed something?

Thanks! :)

**Comment by cx1111** [comment]
You're right that the ann.chan field should refer to the channel of the record that each annotation is from. Seems that the creation of the annotation file is wrong in this field. Chan should be either missing (which defaults to 0) or 0 or 1. I would just ignore this field for this file.

The reason why I didn't make plotrec automatically choose the channel(s) to plot is that when using rdsamp, one could select a subset of channels which would create a mismatch between the output object fields including the signal array, and the channels referred to in the annotation file.

Theoretically, I SHOULD do what you suggest, as in plot annotations depending on the channel, but I have never actually seen anyone use the 'chan' field the way it is supposed to be used. I have also never seen an annotation file contain annotations from multiple channels, which would make plotting all annotations on all chosen channels wrong.

**Comment by Dubrzr** [comment]
Ok thanks for your answer, I see! You are right that I also never seen anyone use plot like this also :)
It seems like nsrdb is all wrong about annotation channels, tomorrow I will have more time to check other dbs:

```
for f in ["16265", "16272", "16273", "16420", "16483", "16539", "16539", "16773", "16773", "16786", "16795", "17052", "17453", "18177", "18184", "19088", "19090", "19093", "19140", "19830"]:
    t = 'data/nsrdb/' + f
    ann = wfdb.rdann(t, 'atr')
    print(numpy.unique(ann.chan))
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0  1  2 16 17 18 32 33 34]
[ 0 16 18 32]
[ 0  1 16 17 32 33]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
[ 0 16 32]
```
This is very strange!

**Comment by Dubrzr** [comment]
Ok, so I tested more datasets, here are the results:


* mitdb: single channel only ([0])
* edb: single channel only ([0])
* afdb: single channel only ([0])
* cudb: single channel only ([0])
* incartdb: single channel only ([0])
* **svdb**: [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [0], [ 0 16 32], [ 0 32], [ 0 80], [0 1], [ 0  1 32], [ 0 16], [ 0 32], [0 1], [ 0 32], [ 0 18 32], [ 0 32], [ 0 18 32 33], [ 0  1 32], [0 1], [ 0 32], [ 0 32], [ 0 32], [ 0 32], [ 0 32], [ 0 32], [ 0 32], [ 0 16 32], [ 0  1 16 18 32 33], [ 0  1 16 17], [ 0 18], [ 0  1 16 17 18 32], [ 0 18 32], [ 0 18 32], [ 0 16], [ 0 32], [ 0 18], [ 0  1 32], [ 0 32], [ 0 18 32], [ 0 16], [ 0 16], [ 0 18], [ 0  1 16 17 32 33]
* **sddb**: [ 0  5  6 14], [ 0  1  5  6 14], [ 0  5  6 14], [ 0  5 14], [ 0  1  5  6 14], [ 0  1  5  6 14], [ 0  5  6 14], [ 0  1  5  6 14], [ 0  5 14], [ 0  5 14], [ 0  5  6 14], [ 0  1  2  3  5  6 14]
* **ltstdb**: [0 5], [ 0  5 14], [ 0  5 14], [ 0  5 14], [0 5], [0 5], [0], [ 0  5 14], [0 5], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  1  5  6 14], [ 0 16 32], [ 0  1 16 17 32], [ 0 16 32], [ 0 16 32 64 80 96], [ 0 16 32], [ 0  5 14], [ 0  5  6 14], [0], [ 0  5 14], [0], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  1  2  5  6 14], [ 0  5 14], [0 5], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  1  5 14], [ 0  5  6 14], [ 0  5 14], [ 0  1  2  5  6 14], [0], [ 0  5 14], [ 0  5 14], [ 0  5 14], [0], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [0], [ 0  5 14], [ 0  5 14], [0], [ 0  5 14], [ 0  5 14], [ 0  1  2  5  6 14], [ 0  5 14], [0 5], [ 0  5 14], [ 0  5  6 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [ 0 14], [ 0  5 14], [ 0  5 14], [ 0  5 14], [0], [ 0  1  5  6 14], [ 0  5 14], [ 0  5 14]
* **ltafdb**: two channel only ([0 99])

So as soon as there is more than one channel, the numbers are wrong...

**Comment by Dubrzr** [comment]
Here are some info on many different databases: https://gist.github.com/Dubrzr/67dfef8069a58a345d1157a84533f1f4

**Comment by cx1111** [comment]
Closing this as it's not really an outstanding issue.
