### ISSUE TITLE
TypeError: The 'annotation' field must be a 'wfdb.Annotation' object in python2, but not python3

### ISSUE THREAD

**Issue by dareneiri** [MIT-LCP/wfdb-python#51]
Unless I am in a python 3 environment, I cannot get annotations to plot. 

```python
import wfdb
import numpy as np
import os
from IPython.display import display

# Following demo.ipynb Example 4
# Can also read the same file hosted on PhysioBank 
annotation2 = wfdb.rdann('100', 'atr', sampfrom = 100000, sampto = 110000, pbdir = 'mitdb')
annotation2.fs = 360
wfdb.plotann(annotation2, timeunits = 'minutes')
```

This results in a TypeError on python2:
```python
/home/spark/anaconda2/envs/waveforms/lib/python2.7/site-packages/wfdb/plots.pyc in checkannplotitems(annotation, title, timeunits)
    286     # signals
    287     if type(annotation)!= annotations.Annotation:
--> 288         raise TypeError("The 'annotation' field must be a 'wfdb.Annotation' object")
    289 
    290     # fs and timeunits

TypeError: The 'annotation' field must be a 'wfdb.Annotation' object
```
But if I print annotation2:
```python
print(type(annotation2))
<type 'instance'>
```

This runs fine in python3 and plots as expected and the object is the same. 

```python
print(type(annotation2))
<class 'wfdb.annotations.Annotation'>

```

I tested this by creating a new/clean conda virtual environment, and switched between python 2 and python 3. 

Is this a known issue? Or am I missing something simple? I'd prefer to run using python 2.

**Comment by cx1111** [comment]
I forgot to make the Annotation object inherit from 'object' which is necessary for python2. Let me know if the latest change has fixed it for you.

**Comment by dareneiri** [comment]
@cx1111 Yes that seemed to do the trick. I can run the code in python 2 without any issue. Thank you for resolving so promptly!
