### ISSUE TITLE
annsamp not containing correct indexes for specific examples.

### ISSUE THREAD

**Issue by Dubrzr** [MIT-LCP/wfdb-python#55]
=========== CODE ===========
```
import wfdb
import numpy

ann = wfdb.rdann('challenge/2014/set-p2/1003', 'atr')

uniq = numpy.unique(ann.annsamp, return_counts=True)
print(uniq)
```

=========== RESULT ===========

> (array([         0, 4294967295, 4294967368, 4294967601, 4294967836,
>        4294968070, 4294968304, 4294968540, 4294968774, 4294969007,
>        4294969239, 4294969470, 4294969702, 4294969933, 4294970165,
>        4294970396, 4294970628, 4294970858, 4294971090, 4294971320,
>        4294971552, 4294971782, 4294972013, 4294972243, 4294972473,
>        4294972703, 4294972933, 4294973163, 4294973392, 4294973621,
>        4294973852, 4294974082, 4294974312, 4294974541, 4294974771,
>        4294975000, 4294975229, 4294975458, 4294975687, 4294975914,
>        4294976143, 4294976370, 4294976598, 4294976825, 4294977052,
>        4294977281, 4294977511, 4294977740, 4294977970, 4294978199,
>        4294978428, 4294978658, 4294978887, 4294979116, 4294979346,
>        4294979576, 4294979805, 4294980033, 4294980262, 4294980490,
>        4294980718, 4294980945, 4294981175, 4294981404, 4294981633,
>        4294981862, 4294982091, 4294982320, 4294982549, 4294982779,
>        4294983008, 4294983237, 4294983466, 4294983695, 4294983924,
>        4294984151, 4294984378, 4294984605, 4294984835, 4294985065,
>        4294985295, 4294985525, 4294985757, 4294985987, 4294986218,
>        4294986448, 4294986678, 4294986911, 4294987141, 4294987373,
>        4294987604, 4294987834, 4294988063, 4294988294, 4294988526,
>        4294988758, 4294988990, 4294989221, 4294989452, 4294989684,
>        4294989916, 4294990147, 4294990378, 4294990609, 4294990840,
>        4294991071, 4294991302, 4294991532, 4294991762, 4294991994,
>        4294992227, 4294992458, 4294992691, 4294992924, 4294993157,
>        4294993390, 4294993622, 4294993854, 4294994086, 4294994316,
>        4294994547, 4294994777, 4294995008, 4294995238, 4294995468,
>        4294995699, 4294995899, 4294996165, 4294996397, 4294996628,
>        4294996859, 4294997090, 4294997321, 4294997551, 4294997781,
>        4294998010, 4294998240, 4294998469, 4294998698, 4294998927,
>        4294999156, 4294999386, 4294999616, 4294999847, 4295000077,
>        4295000307, 4295000536, 4295000766, 4295000994, 4295001223,
>        4295001451, 4295001680, 4295001907, 4295002135, 4295002362,
>        4295002589, 4295002814, 4295003041, 4295003268, 4295003494,
>        4295003723, 4295003951, 4295004181, 4295004408, 4295004637,
>        4295004866, 4295005095, 4295005324, 4295005552, 4295005781,
>        4295006011, 4295006240, 4295006469, 4295006698, 4295006928,
>        4295007158, 4295007389, 4295007619, 4295007849, 4295008078,
>        4295008307, 4295008537, 4295008766, 4295008995, 4295009224,
>        4295009454, 4295009683, 4295009911, 4295010138, 4295010367,
>        4295010598, 4295010828, 4295011058, 4295011289, 4295011519,
>        4295011749, 4295011979, 4295012209, 4295012439, 4295012668,
>        4295012898, 4295013129, 4295013360, 4295013590, 4295013819,
>        4295014050, 4295014282, 4295014514, 4295014747, 4295014983,
>        4295015217, 4295015451, 4295015684, 4295015916, 4295016147,
>        4295016378, 4295016609, 4295016838, 4295017068, 4295017297,
>        4295017525, 4295017754, 4295017984, 4295018214, 4295018445,
>        4295018674, 4295018905, 4295019134, 4295019363, 4295019592,
>        4295019823, 4295020052, 4295020282, 4295020512, 4295020741,
>        4295020970, 4295021198, 4295021426, 4295021655, 4295021884,
>        4295022113, 4295022343, 4295022573, 4295022803, 4295023033,
>        4295023264, 4295023494, 4295023724, 4295023953, 4295024182,
>        4295024412, 4295024640, 4295024868, 4295025096, 4295025326,
>        4295025555, 4295025784, 4295026014, 4295026243, 4295026471,
>        4295026699, 4295026930, 4295027160, 4295027389, 4295027618,
>        4295027846, 4295028075, 4295028303, 4295028530, 4295028759,
>        4295028989, 4295029219, 4295029449, 4295029679, 4295029910,
>        4295030140, 4295030371, 4295030603, 4295030836, 4295031067,
>        4295031299, 4295031531, 4295031763, 4295031995, 4295032225,
>        4295032455, 4295032686, 4295032917, 4295033148, 4295033379,
>        4295033609, 4295033840, 4295034071, 4295034301, 4295034531,
>        4295034761, 4295034991, 4295035220, 4295035449, 4295035677,
>        4295035904, 4295036133, 4295036362, 4295036591, 4295036820,
>        4295037049, 4295037276, 4295037504, 4295037733, 4295037961,
>        4295038190, 4295038419, 4295038649, 4295038879, 4295039109,
>        4295039338, 4295039568, 4295039797, 4295040028, 4295040258,
>        4295040488, 4295040718, 4295040947, 4295041177, 4295041406,
>        4295041635, 4295041865, 4295042094, 4295042324, 4295042553,
>        4295042783, 4295043012, 4295043241, 4295043469, 4295043699,
>        4295043928, 4295044157, 4295044386, 4295044615, 4295044844,
>        4295045074, 4295045304, 4295045535, 4295045766, 4295045998,
>        4295046228, 4295046460, 4295046689, 4295046918, 4295047148,
>        4295047378, 4295047608, 4295047837, 4295048065, 4295048294,
>        4295048521, 4295048749, 4295048977, 4295049204, 4295049431,
>        4295049658, 4295049885, 4295050112, 4295050339, 4295050565,
>        4295050790, 4295051018, 4295051245, 4295051472, 4295051700,
>        4295051928, 4295052155, 4295052383, 4295052611, 4295052838,
>        4295053065, 4295053292, 4295053518, 4295053745, 4295053971,
>        4295054196, 4295054422, 4295054649, 4295054877, 4295055104,
>        4295055331, 4295055558, 4295055785, 4295056011, 4295056238,
>        4295056464, 4295056691, 4295056919, 4295057147, 4295057373,
>        4295057600, 4295057825, 4295058050, 4295058276, 4295058503,
>        4295058729, 4295058955, 4295059180, 4295059405, 4295059630,
>        4295059856, 4295060081, 4295060306, 4295060532, 4295060758,
>        4295060984, 4295061210, 4295061435, 4295061659, 4295061886,
>        4295062112, 4295062340, 4295062567, 4295062794, 4295063020,
>        4295063247, 4295063472, 4295063699, 4295063925, 4295064150,
>        4295064375, 4295064600, 4295064826, 4295065050, 4295065275,
>        4295065499, 4295065726, 4295065954, 4295066180, 4295066407,
>        4295066634, 4295066861, 4295067087, 4295067313, 4295067539,
>        4295067764, 4295067990, 4295068215, 4295068440, 4295068666,
>        4295068890, 4295069114, 4295069340, 4295069567, 4295069793,
>        4295070019, 4295070247, 4295070473, 4295070699, 4295070925,
>        4295071151, 4295071378, 4295071603, 4295071831, 4295072057,
>        4295072283, 4295072509, 4295072734, 4295072960, 4295073188,
>        4295073414, 4295073642, 4295073869, 4295074097, 4295074324,
>        4295074550, 4295074776, 4295075001, 4295075228, 4295075453,
>        4295075678, 4295075903, 4295076127, 4295076351, 4295076576,
>        4295076802, 4295076997, 4295077256, 4295077483, 4295077712,
>        4295077940, 4295078169, 4295078397, 4295078625, 4295078852,
>        4295079079, 4295079307, 4295079535, 4295079763, 4295079989,
>        4295080216, 4295080444, 4295080671, 4295080900, 4295081128,
>        4295081357, 4295081585, 4295081813, 4295082041, 4295082268,
>        4295082496, 4295082725, 4295082953, 4295083182, 4295083409,
>        4295083635, 4295083860, 4295084088, 4295084315, 4295084542,
>        4295084769, 4295084996, 4295085224, 4295085452, 4295085680,
>        4295085909, 4295086137, 4295086365, 4295086595, 4295086823,
>        4295087051, 4295087278, 4295087505, 4295087733, 4295087962,
>        4295088190, 4295088418, 4295088645, 4295088872, 4295089101,
>        4295089329, 4295089557, 4295089785, 4295090014, 4295090243,
>        4295090472, 4295090701, 4295090928, 4295091154, 4295091382,
>        4295091609, 4295091835, 4295092061, 4295092288, 4295092514,
>        4295092739, 4295092965, 4295093191, 4295093418, 4295093644,
>        4295093870, 4295094096, 4295094321, 4295094546, 4295094772,
>        4295094998, 4295095225, 4295095450, 4295095676, 4295095902,
>        4295096127, 4295096352, 4295096578, 4295096803, 4295097028,
>        4295097253, 4295097477, 4295097701, 4295097926, 4295098150,
>        4295098373, 4295098598, 4295098825, 4295099050, 4295099276,
>        4295099501, 4295099727, 4295099952, 4295100177, 4295100402,
>        4295100626, 4295100850, 4295101074, 4295101299, 4295101522,
>        4295101746, 4295101968, 4295102191, 4295102415, 4295102640,
>        4295102864, 4295103089, 4295103315, 4295103540, 4295103765,
>        4295103991, 4295104217, 4295104443, 4295104667, 4295104893,
>        4295105118, 4295105344, 4295105568, 4295105793, 4295106018,
>        4295106245, 4295106472, 4295106699, 4295106926, 4295107153,
>        4295107378, 4295107604, 4295107828, 4295108053, 4295108278,
>        4295108503, 4295108728, 4295108952, 4295109176, 4295109400,
>        4295109625, 4295109851, 4295110077, 4295110303, 4295110528,
>        4295110753, 4295110978, 4295111203, 4295111427, 4295111651,
>        4295111874, 4295112098, 4295112321, 4295112544, 4295112766,
>        4295112988, 4295113210, 4295113434, 4295113657, 4295113880,
>        4295114103, 4295114326, 4295114548, 4295114771, 4295114994,
>        4295115218, 4295115441, 4295115664, 4295115887, 4295116110,
>        4295116333, 4295116556, 4295116778, 4295117001, 4295117224,
>        4295117447, 4295117670, 4295117893, 4295118115, 4295118338,
>        4295118560, 4295118782, 4295119004, 4295119226, 4295119448,
>        4295119670, 4295119892, 4295120113, 4295120334, 4295120555,
>        4295120776, 4295120998, 4295121220, 4295121442, 4295121663,
>        4295121885, 4295122106, 4295122328, 4295122550, 4295122771,
>        4295122993, 4295123216, 4295123438, 4295123659, 4295123880,
>        4295124100, 4295124321, 4295124543, 4295124765, 4295124987,
>        4295125209, 4295125431, 4295125652, 4295125875, 4295126096,
>        4295126317, 4295126538, 4295126759, 4295126980, 4295127201,
>        4295127421, 4295127640, 4295127859, 4295128080, 4295128301,
>        4295128522, 4295128741, 4295128961, 4295129180, 4295129400,
>        4295129620, 4295129840, 4295130060, 4295130281, 4295130501,
>        4295130720, 4295130940, 4295131160, 4295131379, 4295131597,
>        4295131818, 4295132039, 4295132260, 4295132481, 4295132702,
>        4295132923, 4295133144, 4295133364, 4295133584, 4295133804,
>        4295134025, 4295134245, 4295134466, 4295134686, 4295134907,
>        4295135127, 4295135347, 4295135569, 4295135791, 4295136012,
>        4295136233, 4295136455, 4295136677, 4295136898, 4295137119,
>        4295137341, 4295137561, 4295137783, 4295138004, 4295138224,
>        4295138445, 4295138665, 4295138885, 4295139105, 4295139327,
>        4295139548, 4295139769, 4295139991, 4295140211, 4295140432,
>        4295140652, 4295140872, 4295141092, 4295141311, 4295141531,
>        4295141751, 4295141970, 4295142189, 4295142407, 4295142625,
>        4295142845, 4295143065, 4295143284, 4295143504, 4295143724,
>        4295143944, 4295144164, 4295144385, 4295144605, 4295144825,
>        4295145046, 4295145266, 4295145486, 4295145665, 4295145926,
>        4295146146, 4295146365, 4295146586, 4295146807, 4295147029,
>        4295147249, 4295147470, 4295147690, 4295147911, 4295148131,
>        4295148351, 4295148572, 4295148793, 4295149013, 4295149232,
>        4295149413, 4295149669, 4295149887, 4295150106, 4295150326,
>        4295150546, 4295150766, 4295150985, 4295151205, 4295151412,
>        4295151644, 4295151866, 4295152087, 4295152308, 4295152528,
>        4295152748, 4295152968, 4295153188, 4295153407, 4295153626,
>        4295153846, 4295154068, 4295154289, 4295154510, 4295154731,
>        4295154952, 4295155174, 4295155396, 4295155617, 4295155837,
>        4295156057, 4295156277, 4295156496, 4295156716, 4295156935,
>        4295157154, 4295157373, 4295157594, 4295157815, 4295158035,
>        4295158256, 4295158476, 4295158696, 4295158917, 4295159137,
>        4295159357, 4295159577, 4295159797, 4295160016, 4295160236,
>        4295160455, 4295160675, 4295160894, 4295161114, 4295161334,
>        4295161554, 4295161774, 4295161994, 4295162214, 4295162433,
>        4295162653, 4295162874, 4295163094, 4295163314, 4295163534,
>        4295163753, 4295163972, 4295164191, 4295164410, 4295164627,
>        4295164845, 4295165065, 4295165284, 4295165504, 4295165724,
>        4295165944, 4295166164, 4295166384, 4295166604, 4295166824,
>        4295167043, 4295167264, 4295167483, 4295167703, 4295167921,
>        4295168138, 4295168357, 4295168576, 4295168796, 4295169015,
>        4295169234, 4295169453, 4295169671, 4295169891, 4295170110,
>        4295170329, 4295170547, 4295170766, 4295170985, 4295171204,
>        4295171423, 4295171642, 4295171860, 4295172078, 4295172297,
>        4295172517, 4295172738, 4295172958, 4295173179, 4295173400,
>        4295173620, 4295173841, 4295174062, 4295174283, 4295174504,
>        4295174726, 4295174947, 4295175168, 4295175390, 4295175610,
>        4295175833, 4295176057, 4295176280, 4295176504, 4295176728,
>        4295176952, 4295177174, 4295177397, 4295177619, 4295177841,
>        4295178062, 4295178284, 4295178506, 4295178728, 4295178950,
>        4295179169, 4295179389, 4295179610, 4295179833, 4295180054,
>        4295180276, 4295180497, 4295180719, 4295180941, 4295181162,
>        4295181384, 4295181605, 4295181827, 4295182049, 4295182269,
>        4295182490, 4295182710, 4295182930, 4295183150]), array([8, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
>        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

**Comment by cx1111** [comment]
Should be fixed in the latest commit. Now adding custom anncode write functionality into the package.
