### ISSUE TITLE
To do list for rdsamp

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/wfdb-python#6]
- [x] If stacksegments==1 for multi-segment files, preallocate numpy arrays instead of appending lists. 
- [x] sampto and sampfrom selection for multi-segment files
- [x] Support multi-dat single segment files
- [x] Support channel selection. Be aware of variable layout multi-segment case.
- [x] Fix issue of potentially non-consecutive channels being stored in the same dat file in multi-dat records.
- [x] sampto error checking/flag for single segments
- [x] consider byte offset for calculating signal length from file sizes and more.
- [x] remove file size calculation from readdat for completion and put in rdsamp? 
- [x] Allow for samples/frame multi-frequency signals
- [x] Allow for skew
- [x] consider all floating point number regexp for readheader. 
- [x] put in integer nan for multi-seg variable layouts that aren't allocated. Since the large np arrays are of format int64, decide a suitable wfdbnan for the python implementation, possibly -2^63? Or maybe just -2^31.
- [x] Make sure large np array for multi-seg is int64. 
- [x] Configure to allow reading of non-local data files on physionet. Including individual file checking before downloading or not downloading. 
- [x] Prevent multiple downloading and deleting files for multi-segment records if delete files option is chosen.
- [x] Check whether original wfdb package supports skew in multi-segment records and if so, how it deals with them.
- [x] Preference: Sampling frequencies are supposed to be consistent throughout multi-segment signals. Although the fs in the master header is not a mandatory field. Choice to explicitly set all fs in segments, or just leave it and indicate this in documentation.

**Comment by schnyox** [comment]
You should handle when ADCGain is equal to 0 at line 447 in _rdsamp.py according to https://www.physionet.org/physiotools/wag/header-5.htm, i.e. default value of 200.0 should be used in that case. Problem will occur if samples are read for any record in MIT Atrial Fibrillation database for example.
