### ISSUE TITLE
Development of the library with own solutions

### ISSUE THREAD

**Issue by smolendawid** [MIT-LCP/wfdb-python#65]
I am wondering if I could contribute in the wfdb-python with my own solutions and ideas that I find useful? Some of them are not present in the original WFDB package. 

I could add, for example, some clustering algorithms and some visualization, another QRS detection algorithms, waves delineation, filtration, noise estimatiors etc. 

Is it better to contribute or to start new library that uses wfdb-python?

**Comment by Dubrzr** [comment]
Hi @smolendawid !

We recently added a new "processing" module to this wfdb-python package : https://github.com/MIT-LCP/wfdb-python/tree/master/wfdb/processing
It would be great that you integrate more algorithms in this module and we encourage you to do so!

We advise you to fork this project, commit your own algorithms, add tests and documentation, and then make pull requests to this repository.

When you add Python functions, try to make them work for numpy arrays. Don't hesitate to take inspiration from existing functions in the processing module.

Thank you a lot!
