### ISSUE TITLE
record.adcgain NoneType

### ISSUE THREAD

**Issue by davidgutierrez** [MIT-LCP/wfdb-python#70]
for some reason im having problems with the gqrs_detect when i use the mimic data... and i dont know what is wrong with this.
`folder = "p00/p000020"`
`waveform = "p000020-2183-04-28-17-47"`
`sig, fields = wfdb.srdsamp(waveform,pbdir='mimic3wdb/matched/'+folder, sampfrom=t0, sampto=tf)`
`channel = fields['signame'].index("II")`
`record = wfdb.rdsamp(waveform,pbdir='mimic3wdb/matched/'+folder, sampfrom=t0, sampto=tf, channels = [channel])`
`peaks_indexes = wfdb.processing.gqrs_detect(x=sig[:,0], frequency=fields['fs'], adcgain= record.adcgain[0], adczero= record.adczero[0] ,threshold=1.0)`

i get the error: 

> TypeError                                 Traceback (most recent call last)
<ipython-input-70-e51bdce4f5d2> in <module>()
----> 1 peaks_indexes = wfdb.processing.gqrs_detect(x=sig[:,0], frequency=fields['fs'], adcgain= record.adcgain[0], adczero= record.adczero[0] ,threshold=1.0)
TypeError: 'NoneType' object is not subscriptable

**Comment by cx1111** [comment]
Can you paste more of your code? What is sig, etc. Would be nice if it all ran without missing variables.

Also, why are you using srdsamp and rdsamp together?

**Comment by davidgutierrez** [comment]
i just fixed the code so you can see that sig, fields.. etc are declared in the pasted code.  the only missing lines are:
`import wfdb`
`import numpy as np`

They are together because im following the **Peak detection** example that appears in the main page (README.rst).

**Comment by davidgutierrez** [comment]
how the readme was actualiced, the test was actualiced and the error persist....

**Comment by cx1111** [comment]
So there's a new api for gqrs. I do realize the issue with multi-segment records not having these fields. I'm closing this because #7 references this.
