### ISSUE TITLE
scipy dependency

### ISSUE THREAD

**Issue by DSamuylov** [MIT-LCP/wfdb-python#72]
From `setup.py` file:

```
    install_requires=[
        'nose>=1.3.7',
        'numpy>=1.11.0',
        'matplotlib>=1.5.1',
        'requests>=2.10.0',
        'pandas>=0.19.1',
        'scipy==0.19.0'
        ],
```

Why do you restrict the version of `scipy` to be `0.19.0`? Is there any reasons why it wouldn't work with a newer version? Or is it just a typo?

**Comment by Dubrzr** [comment]
Hi Denis,
Primarily for compatibility reasons as a future version could be incompatible, but in fact, we have a CI that tests every commit we do so this can be changed to >=
Is it a problem for you?

**Comment by DSamuylov** [comment]
Thank you for your prompt reply, @Dubrzr!
It is just interesting, why is it different for example for `numpy`? I wondering what happens if a different package depends on a newer version of `scipy`. While installing `wfdb-python`, the newest version of `scipy` has been removed. So, it would break/remove other packages that need it. I think it would be great to have `>=` for all dependencies. Does `scipy` has some APIs that you rely on, but can be changed in future releases?

**Comment by Dubrzr** [comment]
It is simply different because of the habits of two different developers (me and cx1111) : check the git blame at https://github.com/MIT-LCP/wfdb-python/blame/master/setup.py#L60. But you are right, this could break other packages that need it.
