### ISSUE TITLE
gqrs_detect method not returning any peaks

### ISSUE THREAD

**Issue by liandrea4** [MIT-LCP/wfdb-python#76]
Running the example usage code for gqrs-detect doesn't return any peaks when run on the provided sample data file

```
t0 = 10000
tf = 20000
sig, fields = wfdb.srdsamp('../Downloads/100', sampfrom=t0, sampto=tf, channels=[0])
record = wfdb.rdsamp("../Downloads/100", sampfrom=t0, sampto=tf, channels=[0], physical=False)
peaks_indexes = wfdb.processing.gqrs_detect(x=sig[:,0], frequency=fields['fs'], adcgain=record.adcgain[0], adczero=record.adczero[0], threshold=1.0)

plt.plot(sig)
plt.show()

print peaks_indexes
```
The plot looks as expected but the returned peaks is an empty list. 

Running this on version `wfdb-1.3.4`

**Comment by cx1111** [comment]
Trying to make this function more easy to use. In the meantime, the short answer is: the readme is wrong and x should be the digital signal, not the physical signal.
