### ISSUE TITLE
Annotations not showing?

### ISSUE THREAD

**Issue by aerrowfinn72** [MIT-LCP/wfdb-python#78]
![image](https://user-images.githubusercontent.com/17966146/31156239-3d58d7a2-a881-11e7-91e3-f95fc1dc6cc0.png)

I downloaded Record 208 from the database, and this record is known to contain many PVCs (annotated as "V"). The signals above contain many PVCs but have no "V" annotations - only "\*"s are shown. This seems to happen for any record / sample period I try. The only annotations that show are "*"s. Not sure if I'm reading in the annotations incorrectly or an issue elsewhere.

**Comment by cx1111** [comment]
My plotrec functionality is rather limited in that it only plots one symbol (default is the red star), rather than the annotation label symbols. There is nothing being done incorrectly.

I will add the symbol plotting functionality at some point in the future.

**Comment by aerrowfinn72** [comment]
Is the meaning of the star the same as in PhysioBank's [annotations](https://www.physionet.org/physiobank/annotations.shtml)? (i.e. * = systole). How do would I go about choosing and plotting the "V" symbol then?

**Comment by cx1111** [comment]
No, it's just the default symbol for the plotrec function. You can read the doc and input any other style/symbol to plot. The symbols are stored in the Annotation object's `symbol` attribute, and the locations are stored in the object's `sample` attribute.

**Comment by cx1111** [comment]
I added the `plotannsym` argument in `plotrec`.
