### ISSUE TITLE
GQRS detection algorithm

### ISSUE THREAD

**Issue by Gijom** [MIT-LCP/wfdb-python#79]
Hello,

I have a question regarding the GQRS algorithm. It take as input a digitized signal. However in my data pipeline I have only recorded the analog signals and would now like to process these. Would it be ok to apply the algorithm directly with an adcgain of 1 and an adczero of 0 ?

Thanks for your help.

**Comment by cx1111** [comment]
The answer is yes. Sorry for late reply, I didn't know how it worked. I'm rewriting the function this week.
