### ISSUE TITLE
Plotting annotations: Incorrect rounding to integers

### ISSUE THREAD

**Issue by aerrowfinn72** [MIT-LCP/wfdb-python#80]
![image](https://user-images.githubusercontent.com/17966146/31366403-b081b43a-ad3e-11e7-88ce-1b6dd17ad5ac.png)

The annotation locations, when plotted, seem to be rounded to integers, so they are not plotted correctly. I believe that the error is in the function `checkannplotitems `, where the division performed in the section `# Get x axis values to plot` is rounding values to integers instead of using floats/doubles. I believe that the same error is also in the function `checkplotitems `.

**Comment by cx1111** [comment]
Thanks. Sorry for the delay.
