### ISSUE TITLE
Problem when reading files with hyphens

### ISSUE THREAD

**Issue by jesusfbes** [MIT-LCP/wfdb-python#86]
I am trying to read the files in ecfrdvq database. In such database the files are like that:

```
0b61746e-c5f4-4b54-8baa-4404c22e09b5.dat
0b61746e-c5f4-4b54-8baa-4404c22e09b5.hea
```

When reading the records using `rdsamp` the header parsing splits the file name in the hyphens and consequently tries to find the signal at `4404c22e09b5.dat`. Is there any way to circunvent this problem?

**Comment by cx1111** [comment]
I added hyphens to signal name regex. Thanks.

**Comment by jesusfbes** [comment]
Problem Solved. Thank you!!
