### ISSUE TITLE
How to read a *.edf file with rdsamp? 

### ISSUE THREAD

**Issue by Allenlzcoder** [MIT-LCP/wfdb-python#87]
Hello!
    Well,I recently have a problem when using the wfdb-python.While reading a *.edf file the program will encounter errors and it will remind me that there is no *.edf.hea file.Em...I don't konw how to solve this problem.
    Look forward to your reply,sincerely.

**Comment by cx1111** [comment]
Doesn't support edf at the moment sorry! You can use this in the meantime http://pyedflib.readthedocs.io/en/latest/ until I add the support. Will probably call that in a wrapper.

**Comment by maksteel** [comment]
# A workaround is to convert EDF file to MIT format

## Download WFDB and install it locally
see guides at https://physionet.org/physiotools/wfdb.shtml
for MacOS https://physionet.org/physiotools/wfdb-darwin-quick-start.shtml
```
mkdir ~/wfdb
cd ~/wfdb
wget https://physionet.org/physiotools/wfdb.tar.gz
tar xzvf wfdb.tar.gz 
cd wfdb-10.6.2/
./configure
make install WFDBROOT=~/wfdb/
export PATH=$PATH:~/wfdb/bin
```
## Convert single EDF file to MIT format 
e.g. `/dir/where/edf/file/is/stored/Traces.edf`
```
cd /dir/where/edf/file/is/stored/
edf2mit -v -i Traces.edf
```
it will output two files `Traces.dat` and `Traces.hea` in the `/dir/where/edf/file/is/stored/`

Now, you can use `wfdb.rdrecord()` or `wfdb.rdsamp()` to read it.

## Batch convert in python
e.g. 

- `/parent/dir/where/edf/files/are/stored/study1/Traces.edf`
- `/parent/dir/where/edf/files/are/stored/study2/Traces.edf`
- `/parent/dir/where/edf/files/are/stored/study3/Traces.edf`

```
import glob
import subprocess
directory="/parent/dir/where/edf/files/are/stored/" 
edfbin = "~/wfdb/bin/edf2mit"
EDF=[filename for filename in glob.glob(directory+"/**/Traces.edf", recursive=True) ]
for index, recording in enumerate(EDF):
    edfout = subprocess.Popen([edfbin, 
                            '-i', recording,
                            '-r', 'Traces'], 
            stdout=subprocess.PIPE, 
            stderr=subprocess.STDOUT,
            cwd=recording_dir)
    stdout,stderr = edfout.communicate()
    print('output of edf2mit:',stdout)
    if stderr is not None:
        print('edf2mit failed:',stderr)

print("done")
```
it will output two files `Traces.dat` and `Traces.hea` for each `Traces.edf` in its respective sub-dir under `/parent/dir/where/edf/files/are/stored/`

Now, you can use `wfdb.rdrecord()` or `wfdb.rdsamp()` to read it.

**Comment by Lucas-Mc** [comment]
Working on the wrapper now! Hopefully a linked PR is in the future!
