### ISSUE TITLE
unable to install via pip on Python 3.5

### ISSUE THREAD

**Issue by qinfeng** [MIT-LCP/wfdb-python#88]
I have below issue to install wfdb via pip on ubuntu machine with Python 3.5

```
(venv) ubuntu@ip-10-0-0-222 /o/a/api> pip3 install wfdb
Collecting wfdb
  Using cached wfdb-1.3.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-yap6v0ne/wfdb/setup.py", line 18, in <module>
        from wfdb.version import __version__
      File "/tmp/pip-build-yap6v0ne/wfdb/wfdb/__init__.py", line 1, in <module>
        from .readwrite.records import Record, MultiRecord, rdheader, rdsamp, srdsamp, wrsamp, dldatabase, dldatabasefiles
      File "/tmp/pip-build-yap6v0ne/wfdb/wfdb/readwrite/records.py", line 8, in <module>
        import numpy as np
    ImportError: No module named 'numpy'

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-yap6v0ne/wfdb/
```

once I manually install `numpy`, I got another issue as below:

```
(venv) ubuntu@ip-10-0-0-222 /o/a/api> pip3 install numpy
Collecting numpy
  Using cached numpy-1.13.3-cp35-cp35m-manylinux1_x86_64.whl
Installing collected packages: numpy
Successfully installed numpy-1.13.3
(venv) ubuntu@ip-10-0-0-222 /o/a/api> pip3 install wfdb
Collecting wfdb
  Using cached wfdb-1.3.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-h60g9xj7/wfdb/setup.py", line 18, in <module>
        from wfdb.version import __version__
      File "/tmp/pip-build-h60g9xj7/wfdb/wfdb/__init__.py", line 1, in <module>
        from .readwrite.records import Record, MultiRecord, rdheader, rdsamp, srdsamp, wrsamp, dldatabase, dldatabasefiles
      File "/tmp/pip-build-h60g9xj7/wfdb/wfdb/readwrite/records.py", line 14, in <module>
        import requests
    ImportError: No module named 'requests'

Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-h60g9xj7/wfdb/
```

It looks like the dependences are not well managed.

**Comment by qinfeng** [comment]
It looks like setup.py can resolve dependence but it will import wfdb.version first which will import wfdb.__init__ which will require all the dependence to be installed at first place. It then cause the issue.

**Comment by cx1111** [comment]
Hello, thanks very much for raising this. I now made setup.py parse the file instead of importing and uploaded the new version to pypi. Does the pip install work for you now?

**Comment by qinfeng** [comment]
hi, I have no issue to install wfdb==1.3.6 via pip.

but cannot install wfdb==1.3.8 via pip. I just checked the wfdb.egg file which only contains the wfdb folder. requirements.txt file is not included. That's the reason for the issue.

I guess the package tool does not include the requirements file.

**Comment by qinfeng** [comment]
Hi , I think [this commit](https://github.com/MIT-LCP/wfdb-python/commit/c2681e8a4f1dc5d404f80b1d8edd223085250481) introduce above issue.

**Comment by cx1111** [comment]
I had a read of the documentation and they stated that requirements.txt and install_requires serve different purposes. So I removed requirements.txt and put them back into the setup.py file.

Thanks for your help in this.

**Comment by qinfeng** [comment]
Hi, tested and version 1.3.9 works perfectly with pip install. I will close this issue then.
