### ISSUE TITLE
Certain output fields in rdann sometimes become equal to the values of other fields

### ISSUE THREAD

**Issue by cx1111** [MIT-LCP/wfdb-python#9]
Somehow sporadically, (or probably not), running rdann on the exact same file with the same parameters multiple times in succession occasionally ends up with 'chan' equal to 'annsamp', and other similarities.

**Comment by cx1111** [comment]
Found problem. Was allocating arrays with np.empty. I suppose in python even when you declare multiple instances of such objects, they point to the same object if you don't end up filling them. 

Fixed with using np.zeros instead.

**Comment by alistairewj** [comment]
There is an option to declare it as a new entity, isn't there? One of the
optional arguments.

**Comment by cx1111** [comment]
I should have used zeros to begin with anyway as I wanted unset fields like 'chan'  and 'type' to default to 0 like in the wfdb library.
