### ISSUE TITLE
wrsamp does not support writing into a specific folder

### ISSUE THREAD

**Issue by theudas** [MIT-LCP/wfdb-python#90]
the wrsamp function does not support any way to write the file into a specific path.  
  
  wfdb.wrsamp("/home/data/qtdb/resampled_sel233"), fs=fs_target, p_signals=signals, units=fields["units"], signames=fields["signame"], fmt = ['16','16'])  
 
causes     
    recordname must only comprise of letters, digits, hyphens, and underscores.

**Comment by Dubrzr** [comment]
Related to #73
