### ISSUE TITLE
Does this module have all functionalities of WFDB library ?

### ISSUE THREAD

**Issue by gauravbrd** [MIT-LCP/wfdb-python#93]
Hi, I am trying to use this native python module, but I also see swig wrappers for wfdb for python. Do I have to install the wfdb software package and wrap it with swig to use all functionalities or I can use this python module ?

**Comment by alistairewj** [comment]
This is a native python implementation. You do not need SWIG, but not all WFDB functions are implemented. You can consider the SWIG wrappers as a separate entity.

**Comment by gauravbrd** [comment]
Thanks
