### ISSUE TITLE
Error in importing wfdb

### ISSUE THREAD

**Issue by chaira19** [MIT-LCP/wfdb-python#94]
Following error is shown while importing wfdb:

Warning (from warnings module):
  File "F:\Sleep_Disorder_Classification\wfdb\readwrite\_signals.py", line 1190
    reslevels = np.power(2, np.arange(0,33))
RuntimeWarning: invalid value encountered in power

**Comment by cx1111** [comment]
Are you using python 3.5 or 2.7?

**Comment by chaira19** [comment]
I was using 2.7 but it was just a warning. I will also try in 3.5 and let you know if the warning comes.

**Comment by cx1111** [comment]
Moved the line to inside the function. It seems to work.
