### ISSUE TITLE
How to apply the QRS detection algorithm in a set of real physical values of ECG?

### ISSUE THREAD

**Issue by Allenlzcoder** [MIT-LCP/wfdb-python#95]
Well,I still have some questions......
One, for example, there is a set of real physical values of ECG stored in a python array and the sampling frequency of this set of values is known. I want to measure the heart rate using the  wfdb.processing.gqrs_detect() function(or other function?). Could you please give a demo about how to do it?
Two, is there any function in wfdb-python can measure the duration of QRS wave? 
Any useful references about questions?
Thanks a lot!

**Comment by cx1111** [comment]
Latest version 2.0.0 should explain.
